In [1]:
import math
import numpy as np
import pandas as pd
import statsmodels.api as sm

In [2]:
df = pd.read_csv("Second2562_Schedule.csv")
df

,คณะ,Faculty,Student,M_b1030,M_1030_1200,M_1200_1430,M_1430_1600,M_a1600,T_b1030,T_1030_1200,...,S_b1030,S_1030_1200,S_1200_1430,S_1430_1600,S_a1600,N_b1030,N_1030_1200,N_1200_1430,N_1430_1600,N_a1600
0,เกษตร,Agriculture,2035,367,2051,203,90,271,985,3541,...,0,721,16,0,0,0,0,0,0,0
1,บริหารธุรกิจ,Business Administrature,3090,542,580,153,0,0,682,1679,...,194,0,70,0,0,0,69,82,0,0
2,มนุษยศาสตร์,Humanities,2773,655,385,420,399,184,805,629,...,84,30,11,175,0,0,0,0,0,0
3,วนศาสตร์,Forestry,1652,286,435,400,78,0,423,437,...,0,0,0,0,0,0,0,0,0,0
4,วิทยาศาสตร์,Science,3487,1298,628,1279,344,421,1511,489,...,454,321,648,208,681,115,95,1,0,0
5,วิศวกรรมศาสตร์,Engineering,6268,1918,1844,1590,1014,633,1609,2277,...,275,131,258,0,133,97,67,0,32,12
6,ศึกษาศาสตร์,Education,1929,461,184,408,123,6,229,154,...,0,0,0,0,0,0,0,0,0,0
7,เศรษฐศาสตร์,Economics,4132,821,477,821,689,1161,644,283,...,543,0,666,0,0,20,0,118,0,0
8,สถาปัตยกรรมศาสตร์,Architecture,646,149,320,461,0,0,91,417,...,75,0,0,0,0,0,0,0,0,0
9,สังคมศาสตร์,Social Science,3577,746,201,923,749,84,902,174,...,196,0,118,11,169,13,0,0,0,0
10,สัตวแพทยศาสตร์,Veterinary Medicine,478,464,454,131,0,0,504,249,...,54,0,0,0,0,0,0,0,0,0
11,อุตสาหกรรมเกษตร,Agro-Industry,1991,551,372,283,9,38,450,388,...,1,151,29,0,0,0,0,0,0,0
12,เทคนิคการสัตวแพทย์,Veterinary Medicine,727,157,268,301,0,0,258,357,...,2,4,3,0,0,0,5,0,0,0
13,สิ่งแวดล้อม,Environment,658,0,0,0,59,0,53,0,...,0,0,0,0,0,0,0,0,0,0

# 1.i Students according to faculty predict 
#      students according to faculty and class schedule

## Monday before 10:30 ( R-square = 81.9% )

In [3]:
X = df.Student
X = sm.add_constant(X, prepend=False)
Y = df.M_b1030
model = sm.OLS(Y, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                M_b1030   R-squared:                       0.819
Model:                            OLS   Adj. R-squared:                  0.804
Method:                 Least Squares   F-statistic:                     54.47
Date:                Tue, 31 Mar 2020   Prob (F-statistic):           8.50e-06
Time:                        15:20:37   Log-Likelihood:                -94.376
No. Observations:                  14   AIC:                             192.8
Df Residuals:                      12   BIC:                             194.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Student        0.2767      0.037      7.380      0.000       0.195       0.358
const        -59.8681    107.317     -0.558      0.587    -293.691     173.955
==============================================================================
Omnibus:                        2.024   Durbin-Watson:                   1.797
Prob(Omnibus):                  0.364   Jarque-Bera (JB):                1.426
Skew:                           0.741   Prob(JB):                        0.490
Kurtosis:                       2.501   Cond. No.                     5.20e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.2e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  "anyway, n=%i" % int(n))

## Thursday before 10:30 ( R-square = 76.9% )

In [4]:
X = df.Student
X = sm.add_constant(X, prepend=False)
Y = df.R_b1030
model = sm.OLS(Y, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                R_b1030   R-squared:                       0.769
Model:                            OLS   Adj. R-squared:                  0.750
Method:                 Least Squares   F-statistic:                     39.91
Date:                Tue, 31 Mar 2020   Prob (F-statistic):           3.85e-05
Time:                        15:20:37   Log-Likelihood:                -93.598
No. Observations:                  14   AIC:                             191.2
Df Residuals:                      12   BIC:                             192.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Student        0.2240      0.035      6.317      0.000       0.147       0.301
const          7.5341    101.515      0.074      0.942    -213.649     228.717
==============================================================================
Omnibus:                        0.743   Durbin-Watson:                   1.972
Prob(Omnibus):                  0.690   Jarque-Bera (JB):                0.305
Skew:                           0.351   Prob(JB):                        0.859
Kurtosis:                       2.826   Cond. No.                     5.20e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.2e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

## Friday before 10:30 ( R-square = 77.2% )

In [5]:
X = df.Student
X = sm.add_constant(X, prepend=False)
Y = df.F_b1030
model = sm.OLS(Y, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                F_b1030   R-squared:                       0.772
Model:                            OLS   Adj. R-squared:                  0.753
Method:                 Least Squares   F-statistic:                     40.66
Date:                Tue, 31 Mar 2020   Prob (F-statistic):           3.52e-05
Time:                        15:20:37   Log-Likelihood:                -93.664
No. Observations:                  14   AIC:                             191.3
Df Residuals:                      12   BIC:                             192.6
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Student        0.2272      0.036      6.376      0.000       0.150       0.305
const        -33.1385    101.992     -0.325      0.751    -255.361     189.084
==============================================================================
Omnibus:                        2.522   Durbin-Watson:                   1.960
Prob(Omnibus):                  0.283   Jarque-Bera (JB):                1.416
Skew:                           0.776   Prob(JB):                        0.493
Kurtosis:                       2.869   Cond. No.                     5.20e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.2e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

## Tuesday 12:00 - 14:30 ( R-square = 80.0% )

In [6]:
X = df.Student
X = sm.add_constant(X, prepend=False)
Y = df.T_1200_1430
model = sm.OLS(Y, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            T_1200_1430   R-squared:                       0.800
Model:                            OLS   Adj. R-squared:                  0.783
Method:                 Least Squares   F-statistic:                     47.93
Date:                Tue, 31 Mar 2020   Prob (F-statistic):           1.60e-05
Time:                        15:20:37   Log-Likelihood:                -94.635
No. Observations:                  14   AIC:                             193.3
Df Residuals:                      12   BIC:                             194.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Student        0.2644      0.038      6.923      0.000       0.181       0.348
const        -25.7240    109.321     -0.235      0.818    -263.915     212.467
==============================================================================
Omnibus:                        1.372   Durbin-Watson:                   1.524
Prob(Omnibus):                  0.504   Jarque-Bera (JB):                0.258
Skew:                           0.301   Prob(JB):                        0.879
Kurtosis:                       3.283   Cond. No.                     5.20e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.2e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

## Monday 14:30 - 16:00 ( R-square = 77.5% )

In [7]:
X = df.Student
X = sm.add_constant(X, prepend=False)
Y = df.M_1430_1600
model = sm.OLS(Y, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            M_1430_1600   R-squared:                       0.775
Model:                            OLS   Adj. R-squared:                  0.756
Method:                 Least Squares   F-statistic:                     41.37
Date:                Tue, 31 Mar 2020   Prob (F-statistic):           3.25e-05
Time:                        15:20:37   Log-Likelihood:                -90.361
No. Observations:                  14   AIC:                             184.7
Df Residuals:                      12   BIC:                             186.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Student        0.1810      0.028      6.432      0.000       0.120       0.242
const       -178.5343     80.561     -2.216      0.047    -354.062      -3.007
==============================================================================
Omnibus:                        3.691   Durbin-Watson:                   1.760
Prob(Omnibus):                  0.158   Jarque-Bera (JB):                1.426
Skew:                          -0.702   Prob(JB):                        0.490
Kurtosis:                       3.686   Cond. No.                     5.20e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.2e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

## Thursday 14:30 - 16:00 ( R-square = 76.8% )

In [8]:
X = df.Student
X = sm.add_constant(X, prepend=False)
Y = df.R_1430_1600
model = sm.OLS(Y, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            R_1430_1600   R-squared:                       0.768
Model:                            OLS   Adj. R-squared:                  0.749
Method:                 Least Squares   F-statistic:                     39.81
Date:                Tue, 31 Mar 2020   Prob (F-statistic):           3.89e-05
Time:                        15:20:37   Log-Likelihood:                -85.060
No. Observations:                  14   AIC:                             174.1
Df Residuals:                      12   BIC:                             175.4
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Student        0.1216      0.019      6.310      0.000       0.080       0.164
const       -106.6258     55.166     -1.933      0.077    -226.822      13.570
==============================================================================
Omnibus:                        0.010   Durbin-Watson:                   1.379
Prob(Omnibus):                  0.995   Jarque-Bera (JB):                0.140
Skew:                          -0.013   Prob(JB):                        0.932
Kurtosis:                       2.510   Cond. No.                     5.20e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.2e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

# 1.ii Regression model

## Tuesday 12:00 - 14:30

In [9]:
df2 = df[['Faculty', 'Student', 'T_1200_1430']].copy()
df2 = df2.assign(predict = -25.7240 + df2.Student*0.2644) 
df2

                    Faculty  Student  T_1200_1430    predict
0               Agriculture     2035          296   512.3300
1   Business Administrature     3090          391   791.2720
2                Humanities     2773          722   707.4572
3                  Forestry     1652          441   411.0648
4                   Science     3487         1372   896.2388
5               Engineering     6268         1737  1631.5352
6                 Education     1929          373   484.3036
7                 Economics     4132          830  1066.7768
8              Architecture      646          402   145.0784
9            Social Science     3577         1034   920.0348
10      Veterinary Medicine      478          130   100.6592
11            Agro-Industry     1991          431   500.6964
12      Veterinary Medicine      727          244   166.4948
13              Environment      658           79   148.2512

In [10]:
from sklearn.metrics import mean_squared_error
from math import sqrt

In [11]:
RMSE = sqrt(mean_squared_error(df2.T_1200_1430, df2.predict))
RMSE

208.66330890665537

In [12]:
def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [13]:
MAPE = mean_absolute_percentage_error(df2.T_1200_1430, df2.predict)
MAPE

36.890796570220566

# 2.1.i Regression from all feature set

In [14]:
df_pax = pd.read_csv("Regression_Data-pax.csv")
df_pax

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,พหล,8:00-8:30,175,145,18,201.20160,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
1,พหล,8:30-9:00,126,110,22,0.89112,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
2,พหล,9:00-9:30,99,90,24,225.58680,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
3,พหล,9:30-10:00,79,74,26,401.78130,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
4,พหล,10:00-10:30,42,42,15,248.13950,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
5,สระน้ำ พหล,8:00-8:30,58,97,3,0.00000,98.000000,27.00000,5270.0000,35.0000,2.000,33.00,2.000,8,2,1
6,สระน้ำ พหล,8:30-9:00,18,89,2,0.00000,98.000000,27.00000,5270.0000,35.0000,2.000,33.00,2.000,8,2,1
7,สระน้ำ พหล,9:00-9:30,16,39,1,159.00000,98.000000,27.00000,5270.0000,35.0000,2.000,33.00,2.000,8,2,1
8,สระน้ำ พหล,9:30-10:00,17,58,8,217.00000,98.000000,27.00000,5270.0000,35.0000,2.000,33.00,2.000,8,2,1
9,สระน้ำ พหล,10:00-10:30,18,50,16,126.00000,98.000000,27.00000,5270.0000,35.0000,2.000,33.00,2.000,8,2,1
10,งาม1,8:00-8:30,71,9,25,447.32000,18090.000000,816.00000,265234.6525,159.0000,6.000,69.00,3.000,13,4,2
11,งาม1,8:30-9:00,111,21,26,317.83000,18090.000000,816.00000,265234.6525,159.0000,6.000,69.00,3.000,13,4,2
12,งาม1,9:00-9:30,66,41,26,2837.62000,18090.000000,816.00000,265234.6525,159.0000,6.000,69.00,3.000,13,4,2
13,งาม1,9:30-10:00,34,19,33,885.59000,18090.000000,816.00000,265234.6525,159.0000,6.000,69.00,3.000,13,4,2
14,งาม1,10:00-10:30,42,15,8,575.56000,18090.000000,816.00000,265234.6525,159.0000,6.000,69.00,3.000,13,4,2
15,งาม3,8:00-8:30,18,7,2,777.00000,14718.000000,560.00000,195262.2497,170.0000,0.000,69.00,5.000,9,1,3
16,งาม3,8:30-9:00,8,1,4,340.00000,14718.000000,560.00000,195262.2497,170.0000,0.000,69.00,5.000,9,1,3
17,งาม3,9:00-9:30,0,1,3,2802.00000,14718.000000,560.00000,195262.2497,170.0000,0.000,69.00,5.000,9,1,3
18,งาม3,9:30-10:00,0,0,4,742.00000,14718.000000,560.00000,195262.2497,170.0000,0.000,69.00,5.000,9,1,3
19,งาม3,10:00-10:30,0,0,3,430.00000,14718.000000,560.00000,195262.2497,170.0000,0.000,69.00,5.000,9,1,3
20,วิภา,8:00-8:30,35,2,24,862.00000,1892.000000,358.00000,93389.1200,99.0000,0.000,6.00,9.000,78,2,1
21,วิภา,8:30-9:00,81,54,23,163.00000,1892.000000,358.00000,93389.1200,99.0000,0.000,6.00,9.000,78,2,1
22,วิภา,9:00-9:30,75,50,22,318.00000,1892.000000,358.00000,93389.1200,99.0000,0.000,6.00,9.000,78,2,1
23,วิภา,9:30-10:00,32,18,12,1474.00000,1892.000000,358.00000,93389.1200,99.0000,0.000,6.00,9.000,78,2,1
24,วิภา,10:00-10:30,23,10,9,244.00000,1892.000000,358.00000,93389.1200,99.0000,0.000,6.00,9.000,78,2,1
25,ศร.1,8:00-8:30,5,7,20,4617.00000,24503.000000,1221.00000,349200.0000,280.0000,5.000,92.00,7.000,0,2,2
26,ศร.1,8:30-9:00,1,4,15,1322.00000,24503.000000,1221.00000,349200.0000,280.0000,5.000,92.00,7.000,0,2,2
27,ศร.1,9:00-9:30,1,7,14,4647.00000,24503.000000,1221.00000,349200.0000,280.0000,5.000,92.00,7.000,0,2,2
28,ศร.1,9:30-10:00,4,5,5,5341.00000,24503.000000,1221.00000,349200.0000,280.0000,5.000,92.00,7.000,0,2,2
29,ศร.1,10:00-10:30,0,3,6,1940.00000,24503.000000,1221.00000,349200.0000,280.0000,5.000,92.00,7.000,0,2,2
30,หอสมุด,8:00-8:30,2,8,26,41.00000,22621.000000,1648.00000,247210.0000,244.0000,1.000,6.00,75.000,71,3,0
31,หอสมุด,8:30-9:00,0,4,33,0.00000,22621.000000,1648.00000,247210.0000,244.0000,1.000,6.00,75.000,71,3,0
32,หอสมุด,9:00-9:30,2,0,13,20.00000,22621.000000,1648.00000,247210.0000,244.0000,1.000,6.00,75.000,71,3,0
33,หอสมุด,9:30-10:00,1,10,20,0.00000,22621.000000,1648.00000,247210.0000,244.0000,1.000,6.00,75.000,71,3,0
34,หอสมุด,10:00-10:30,2,10,6,75.00000,22621.000000,1648.00000,247210.0000,244.0000,1.000,6.00,75.000,71,3,0
35,บาร์ใหม่,8:00-8:30,3,6,2,4218.37982,23519.000000,1470.00000,319558.2243,207.0000,3.000,71.00,8.000,10,1,3
36,บาร์ใหม่,8:30-9:00,0,0,3,1232.26505,23519.000000,1470.00000,319558.2243,207.0000,3.000,71.00,8.000,10,1,3
37,บาร์ใหม่,9:00-9:30,1,2,4,3928.40932,23519.000000,1470.00000,319558.2243,207.0000,3.000,71.00,8.000,10,1,3
38,บาร์ใหม่,9:30-10:00,0,0,5,4246.83225,23519.000000,1470.00000,319558.2243,207.0000,3.000,71.00,8.000,10,1,3
39,บาร์ใหม่,10:00-10:30,2,0,0,1202.36152,23519.000000,1470.00000,319558.2243,207.0000,3.000,71.00,8.000,10,1,3
40,อาคารจักร,8:00-8:30,0,0,14,4535.00000,21017.000000,1972.00000,352377.6914,211.0000,0.000,91.00,8.000,0,1,0
41,อาคารจักร,8:30-9:00,0,0,30,1069.00000,21017.000000,1972.00000,352377.6914,211.0000,0.000,91.00,8.000,0,1,0
42,อาคารจักร,9:00-9:30,3,3,24,2466.00000,21017.000000,1972.00000,352377.6914,211.0000,0.000,91.00,8.000,0,1,0
43,อาคารจักร,9:30-10:00,3,4,26,5142.00000,21017.000000,1972.00000,352377.6914,211.0000,0.000,91.00,8.000,0,1,0
44,อาคารจักร,10:00-10:30,2,1,9,2238.00000,21017.000000,1972.00000,352377.6914,211.0000,0.000,91.00,8.000,0,1,0
45,RDIPT,8:00-8:30,4,1,32,2737.00000,18716.000000,1801.00000,316241.5301,91.0000,0.000,55.00,1.000,10,1,0
46,RDIPT,8:30-9:00,0,3,19,834.00000,18716.000000,1801.00000,316241.5301,91.0000,0.000,55.00,1.000,10,1,0
47,RDIPT,9:00-9:30,10,13,22,1337.00000,18716.000000,1801.00000,316241.5301,91.0000,0.000,55.00,1.000,10,1,0
48,RDIPT,9:30-10:00,0,5,17,4066.00000,18716.000000,1801.00000,316241.5301,91.0000,0.000,55.00,1.000,10,1,0
49,RDIPT,10:00-10:30,7,3,17,1904.00000,18716.000000,1801.00000,316241.5301,91.0000,0.000,55.00,1.000,10,1,0

## min-max normalization

In [15]:
df_paxx = df_pax.iloc[:,5:].copy()
df_paxx.head()

,#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,201.20160,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
1,0.89112,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
2,225.58680,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
3,401.78130,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
4,248.13950,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2

In [16]:
normalized_df_paxx=(df_paxx-df_paxx.min())/(df_paxx.max()-df_paxx.min())
normalized_df_paxx.head()

,#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,0.037671,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
1,0.000167,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
2,0.042237,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
3,0.075226,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
4,0.046459,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667

In [17]:
df_pax = pd.concat([df_pax.iloc[:,:5],normalized_df_paxx], axis=1)

In [18]:
df_pax

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,พหล,8:00-8:30,175,145,18,0.037671,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
1,พหล,8:30-9:00,126,110,22,0.000167,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
2,พหล,9:00-9:30,99,90,24,0.042237,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
3,พหล,9:30-10:00,79,74,26,0.075226,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
4,พหล,10:00-10:30,42,42,15,0.046459,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
5,สระน้ำ พหล,8:00-8:30,58,97,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
6,สระน้ำ พหล,8:30-9:00,18,89,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
7,สระน้ำ พหล,9:00-9:30,16,39,1,0.029770,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
8,สระน้ำ พหล,9:30-10:00,17,58,8,0.040629,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
9,สระน้ำ พหล,10:00-10:30,18,50,16,0.023591,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
10,งาม1,8:00-8:30,71,9,25,0.083752,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
11,งาม1,8:30-9:00,111,21,26,0.059508,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
12,งาม1,9:00-9:30,66,41,26,0.531290,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
13,งาม1,9:30-10:00,34,19,33,0.165810,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
14,งาม1,10:00-10:30,42,15,8,0.107763,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
15,งาม3,8:00-8:30,18,7,2,0.145478,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
16,งาม3,8:30-9:00,8,1,4,0.063658,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
17,งาม3,9:00-9:30,0,1,3,0.524621,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
18,งาม3,9:30-10:00,0,0,4,0.138925,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
19,งาม3,10:00-10:30,0,0,3,0.080509,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
20,วิภา,8:00-8:30,35,2,24,0.161393,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
21,วิภา,8:30-9:00,81,54,23,0.030519,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
22,วิภา,9:00-9:30,75,50,22,0.059539,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
23,วิภา,9:30-10:00,32,18,12,0.275978,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
24,วิภา,10:00-10:30,23,10,9,0.045684,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
25,ศร.1,8:00-8:30,5,7,20,0.864445,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
26,ศร.1,8:30-9:00,1,4,15,0.247519,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
27,ศร.1,9:00-9:30,1,7,14,0.870062,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
28,ศร.1,9:30-10:00,4,5,5,1.000000,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
29,ศร.1,10:00-10:30,0,3,6,0.363228,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
30,หอสมุด,8:00-8:30,2,8,26,0.007676,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
31,หอสมุด,8:30-9:00,0,4,33,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
32,หอสมุด,9:00-9:30,2,0,13,0.003745,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
33,หอสมุด,9:30-10:00,1,10,20,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
34,หอสมุด,10:00-10:30,2,10,6,0.014042,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
35,บาร์ใหม่,8:00-8:30,3,6,2,0.789811,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
36,บาร์ใหม่,8:30-9:00,0,0,3,0.230718,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
37,บาร์ใหม่,9:00-9:30,1,2,4,0.735519,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
38,บาร์ใหม่,9:30-10:00,0,0,5,0.795138,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
39,บาร์ใหม่,10:00-10:30,2,0,0,0.225119,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
40,อาคารจักร,8:00-8:30,0,0,14,0.849092,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
41,อาคารจักร,8:30-9:00,0,0,30,0.200150,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
42,อาคารจักร,9:00-9:30,3,3,24,0.461711,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
43,อาคารจักร,9:30-10:00,3,4,26,0.962741,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
44,อาคารจักร,10:00-10:30,2,1,9,0.419023,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
45,RDIPT,8:00-8:30,4,1,32,0.512451,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
46,RDIPT,8:30-9:00,0,3,19,0.156151,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
47,RDIPT,9:00-9:30,10,13,22,0.250328,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
48,RDIPT,9:30-10:00,0,5,17,0.761281,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
49,RDIPT,10:00-10:30,7,3,17,0.356488,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [19]:
df_pax_pred = df_pax.copy()

In [20]:
X = df_pax.iloc[:,5:]
X = sm.add_constant(X, prepend=False)
Y = df_pax['#waiting passengers (y)']
model = sm.OLS(Y, X)
resultss = model.fit()
df_pax_pred = df_pax_pred.assign(predict_waiting_passengers = resultss.predict(X))
print(resultss.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       0.760
Model:                                 OLS   Adj. R-squared:                  0.698
Method:                      Least Squares   F-statistic:                     12.34
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):           2.87e-09
Time:                             15:20:38   Log-Likelihood:                -218.27
No. Observations:                       50   AIC:                             458.5
Df Residuals:                           39   BIC:                             479.6
Df Model:                               10
Covariance Type:                 nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings     -7.2797     16.102     -0.452      0.654     -39.850      25.290
#students from faculties   -293.8290    131.828     -2.229      0.032    -560.477     -27.181
#lecturers from faculties     1.2859     89.199      0.014      0.989    -179.136     181.708
faculty area                280.4640    200.903      1.396      0.171    -125.900     686.828
#stores                     -71.4844     34.430     -2.076      0.045    -141.126      -1.843
#banks                       15.7436     30.367      0.518      0.607     -45.679      77.166
#offices                     46.5872     27.469      1.696      0.098      -8.974     102.148
#dorms                      133.5600    105.638      1.264      0.214     -80.114     347.234
#waiting seats                0.6585     36.980      0.018      0.986     -74.140      75.457
#routes                      47.4779     37.456      1.268      0.212     -28.284     123.240
#main entrances              58.1149     18.507      3.140      0.003      20.681      95.548
const                       -31.4072     20.624     -1.523      0.136     -73.123      10.309
==============================================================================
Omnibus:                       15.722   Durbin-Watson:                   1.498
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               45.061
Skew:                           0.618   Prob(JB):                     1.64e-10
Kurtosis:                       7.483   Cond. No.                     3.24e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.64e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [21]:
X = df_pax.iloc[:,5:]
X = sm.add_constant(X, prepend=False)
Y = df_pax['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_pred = df_pax_pred.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       0.795
Model:                                   OLS   Adj. R-squared:                  0.743
Method:                        Least Squares   F-statistic:                     15.14
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):           1.52e-10
Time:                               15:20:38   Log-Likelihood:                -207.07
No. Observations:                         50   AIC:                             436.1
Df Residuals:                             39   BIC:                             457.2
Df Model:                                 10
Covariance Type:                   nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings      2.1022     12.869      0.163      0.871     -23.928      28.133
#students from faculties   -523.8776    105.359     -4.972      0.000    -736.987    -310.768
#lecturers from faculties   -86.6505     71.289     -1.215      0.231    -230.846      57.546
faculty area                527.2063    160.565      3.283      0.002     202.433     851.979
#stores                    -113.1243     27.517     -4.111      0.000    -168.783     -57.466
#banks                       85.6543     24.270      3.529      0.001      36.564     134.744
#offices                     12.9820     21.953      0.591      0.558     -31.423      57.387
#dorms                      369.9579     84.428      4.382      0.000     199.186     540.730
#waiting seats             -104.0781     29.555     -3.522      0.001    -163.858     -44.298
#routes                     -61.0418     29.936     -2.039      0.048    -121.592      -0.491
#main entrances              52.9289     14.791      3.578      0.001      23.011      82.846
const                        42.3128     16.483      2.567      0.014       8.973      75.653
==============================================================================
Omnibus:                       10.909   Durbin-Watson:                   1.614
Prob(Omnibus):                  0.004   Jarque-Bera (JB):               27.270
Skew:                           0.293   Prob(JB):                     1.20e-06
Kurtosis:                       6.570   Cond. No.                     3.24e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.64e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [22]:
X = df_pax.iloc[:,5:]
X = sm.add_constant(X, prepend=False)
Y = df_pax['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_pred = df_pax_pred.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       0.613
Model:                                  OLS   Adj. R-squared:                  0.513
Method:                       Least Squares   F-statistic:                     6.168
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):           1.44e-05
Time:                              15:20:38   Log-Likelihood:                -161.44
No. Observations:                        50   AIC:                             344.9
Df Residuals:                            39   BIC:                             365.9
Df Model:                                10
Covariance Type:                  nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings      0.4427      5.167      0.086      0.932     -10.008      10.893
#students from faculties    -21.5235     42.298     -0.509      0.614    -107.079      64.032
#lecturers from faculties   -10.8368     28.620     -0.379      0.707     -68.726      47.052
faculty area                 47.8650     64.460      0.743      0.462     -82.519     178.249
#stores                     -10.5453     11.047     -0.955      0.346     -32.890      11.800
#banks                       -7.3783      9.743     -0.757      0.453     -27.086      12.329
#offices                      6.0350      8.813      0.685      0.498     -11.792      23.862
#dorms                        4.9637     33.895      0.146      0.884     -63.594      73.522
#waiting seats                5.5191     11.865      0.465      0.644     -18.480      29.519
#routes                      18.6939     12.018      1.555      0.128      -5.615      43.003
#main entrances              -9.6414      5.938     -1.624      0.112     -21.652       2.369
const                         2.9058      6.617      0.439      0.663     -10.479      16.291
==============================================================================
Omnibus:                        0.773   Durbin-Watson:                   2.197
Prob(Omnibus):                  0.680   Jarque-Bera (JB):                0.473
Skew:                          -0.238   Prob(JB):                        0.790
Kurtosis:                       3.013   Cond. No.                     3.24e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.64e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [23]:
df_pax_pred

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances,predict_waiting_passengers,predict_departing_passengers,predict_arriving_passengers
0,พหล,8:00-8:30,175,145,18,0.037671,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667,104.219516,92.194364,20.998813
1,พหล,8:30-9:00,126,110,22,0.000167,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667,104.492535,92.115522,20.982209
2,พหล,9:00-9:30,99,90,24,0.042237,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667,104.186279,92.203962,21.000834
3,พหล,9:30-10:00,79,74,26,0.075226,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667,103.946129,92.273312,21.015439
4,พหล,10:00-10:30,42,42,15,0.046459,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667,104.155540,92.212839,21.002704
5,สระน้ำ พหล,8:00-8:30,58,97,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333,25.536843,66.560483,5.991678
6,สระน้ำ พหล,8:30-9:00,18,89,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333,25.536843,66.560483,5.991678
7,สระน้ำ พหล,9:00-9:30,16,39,1,0.029770,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333,25.320129,66.623065,6.004857
8,สระน้ำ พหล,9:30-10:00,17,58,8,0.040629,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333,25.241076,66.645894,6.009665
9,สระน้ำ พหล,10:00-10:30,18,50,16,0.023591,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333,25.365108,66.610076,6.002122
10,งาม1,8:00-8:30,71,9,25,0.083752,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667,65.570717,20.777433,23.553128
11,งาม1,8:30-9:00,111,21,26,0.059508,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667,65.747209,20.726466,23.542395
12,งาม1,9:00-9:30,66,41,26,0.531290,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667,62.312783,21.718255,23.751261
13,งาม1,9:30-10:00,34,19,33,0.165810,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667,64.973363,20.949936,23.589457
14,งาม1,10:00-10:30,42,15,8,0.107763,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667,65.395928,20.827909,23.563758
15,งาม3,8:00-8:30,18,7,2,0.145478,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000,5.528751,1.705064,3.180007
16,งาม3,8:30-9:00,8,1,4,0.063658,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000,6.124374,1.533061,3.143784
17,งาม3,9:00-9:30,0,1,3,0.524621,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000,2.768714,2.502103,3.347860
18,งาม3,9:30-10:00,0,0,4,0.138925,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000,5.576455,1.691288,3.177106
19,งาม3,10:00-10:30,0,0,3,0.080509,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000,6.001706,1.568485,3.151244
20,วิภา,8:00-8:30,35,2,24,0.161393,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333,48.859527,26.898321,18.020706
21,วิภา,8:30-9:00,81,54,23,0.030519,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333,49.812251,26.623195,17.962766
22,วิภา,9:00-9:30,75,50,22,0.059539,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333,49.600989,26.684203,17.975614
23,วิภา,9:30-10:00,32,18,12,0.275978,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333,48.025383,27.139204,18.071435
24,วิภา,10:00-10:30,23,10,9,0.045684,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333,49.701850,26.655077,17.969480
25,ศร.1,8:00-8:30,5,7,20,0.864445,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667,0.777593,5.610761,12.086504
26,ศร.1,8:30-9:00,1,4,15,0.247519,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667,5.268616,4.313849,11.813381
27,ศร.1,9:00-9:30,1,7,14,0.870062,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667,0.736703,5.622569,12.088991
28,ศร.1,9:30-10:00,4,5,5,1.000000,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667,-0.209206,5.895727,12.146517
29,ศร.1,10:00-10:30,0,3,6,0.363228,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667,4.426294,4.557094,11.864607
30,หอสมุด,8:00-8:30,2,8,26,0.007676,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000,1.381191,6.405432,19.601144
31,หอสมุด,8:30-9:00,0,4,33,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000,1.437073,6.389294,19.597745
32,หอสมุด,9:00-9:30,2,0,13,0.003745,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000,1.409813,6.397166,19.599403
33,หอสมุด,9:30-10:00,1,10,20,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000,1.437073,6.389294,19.597745
34,หอสมุด,10:00-10:30,2,10,6,0.014042,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000,1.334849,6.418814,19.603962
35,บาร์ใหม่,8:00-8:30,3,6,2,0.789811,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000,-0.507448,2.093074,2.903839
36,บาร์ใหม่,8:30-9:00,0,0,3,0.230718,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000,3.562571,0.917740,2.656319
37,บาร์ใหม่,9:00-9:30,1,2,4,0.735519,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000,-0.112223,1.978942,2.879804
38,บาร์ใหม่,9:30-10:00,0,0,5,0.795138,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000,-0.546228,2.104273,2.906198
39,บาร์ใหม่,10:00-10:30,2,0,0,0.225119,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000,3.603329,0.905970,2.653840
40,อาคารจักร,8:00-8:30,0,0,14,0.849092,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000,-0.369508,2.168752,20.719777
41,อาคารจักร,8:30-9:00,0,0,30,0.200150,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000,4.354585,0.804535,20.432479
42,อาคารจักร,9:00-9:30,3,3,24,0.461711,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000,2.450500,1.354394,20.548276
43,อาคารจักร,9:30-10:00,3,4,26,0.962741,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000,-1.196837,2.407667,20.770091
44,อาคารจักร,10:00-10:30,2,1,9,0.419023,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000,2.761260,1.264653,20.529377
45,RDIPT,8:00-8:30,4,1,32,0.512451,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000,3.434822,5.220967,21.446535
46,RDIPT,8:30-9:00,0,3,19,0.156151,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000,6.028576,4.471946,21.288794
47,RDIPT,9:00-9:30,10,13,22,0.250328,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000,5.342996,4.669927,21.330488
48,RDIPT,9:30-10:00,0,5,17,0.761281,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000,1.623420,5.744061,21.556696
49,RDIPT,10:00-10:30,7,3,17,0.356488,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000,4.570186,4.893098,21.377487

In [24]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_pred['#waiting passengers (y)'], df_pax_pred['predict_waiting_passengers']))
RMSE_waiting_passengers

19.040066993761275

In [25]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_pred['#departing passengers (y)'], df_pax_pred['predict_departing_passengers']))
RMSE_departing_passengers

15.217147095247244

In [26]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_pred['#arriving passengers (y)'], df_pax_pred['predict_arriving_passengers']))
RMSE_arriving_passengers

6.109089405047783

# 2.1.ii Regression from some feature set classify by time

## 8:00 - 8:30

In [27]:
df_pax_800 = df_pax[df_pax['time'] == '8:00-8:30'].copy()
df_pax_800

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,พหล,8:00-8:30,175,145,18,0.037671,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
5,สระน้ำ พหล,8:00-8:30,58,97,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
10,งาม1,8:00-8:30,71,9,25,0.083752,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
15,งาม3,8:00-8:30,18,7,2,0.145478,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
20,วิภา,8:00-8:30,35,2,24,0.161393,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
25,ศร.1,8:00-8:30,5,7,20,0.864445,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
30,หอสมุด,8:00-8:30,2,8,26,0.007676,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
35,บาร์ใหม่,8:00-8:30,3,6,2,0.789811,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
40,อาคารจักร,8:00-8:30,0,0,14,0.849092,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
45,RDIPT,8:00-8:30,4,1,32,0.512451,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [28]:
X = df_pax_800.iloc[:,[7,8,9,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_800['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_800 = df_pax_800.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       0.847
Model:                                 OLS   Adj. R-squared:                  0.541
Method:                      Least Squares   F-statistic:                     2.765
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):              0.217
Time:                             15:20:38   Log-Likelihood:                -44.288
No. Observations:                       10   AIC:                             102.6
Df Residuals:                            3   BIC:                             104.7
Df Model:                                6
Covariance Type:                 nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#lecturers from faculties  -207.0363    130.846     -1.582      0.212    -623.447     209.375
faculty area                130.7422    183.669      0.712      0.528    -453.773     715.257
#stores                    -364.7833    136.730     -2.668      0.076    -799.920      70.354
#offices                    433.5526    193.189      2.244      0.111    -181.261    1048.366
#dorms                      304.5102    136.445      2.232      0.112    -129.718     738.738
#waiting seats              220.7308    112.200      1.967      0.144    -136.340     577.801
const                      -110.9463     90.715     -1.223      0.309    -399.643     177.750
==============================================================================
Omnibus:                        1.740   Durbin-Watson:                   1.409
Prob(Omnibus):                  0.419   Jarque-Bera (JB):                0.437
Skew:                          -0.510   Prob(JB):                        0.804
Kurtosis:                       3.086   Cond. No.                         36.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))

In [29]:
X = df_pax_800.iloc[:,[5,7,9,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_800['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_800 = df_pax_800.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       0.906
Model:                                   OLS   Adj. R-squared:                  0.719
Method:                        Least Squares   F-statistic:                     4.848
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):              0.112
Time:                               15:20:38   Log-Likelihood:                -40.993
No. Observations:                         10   AIC:                             95.99
Df Residuals:                              3   BIC:                             98.10
Df Model:                                  6
Covariance Type:                   nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings    178.6394     69.677      2.564      0.083     -43.103     400.382
#lecturers from faculties  -234.6549     62.362     -3.763      0.033    -433.120     -36.190
#stores                    -444.5252    119.283     -3.727      0.034    -824.137     -64.914
#offices                    440.5200    150.121      2.934      0.061     -37.232     918.272
#dorms                      505.7677    139.810      3.618      0.036      60.831     950.705
#waiting seats              141.6496     82.357      1.720      0.184    -120.447     403.746
const                       -55.4944     67.993     -0.816      0.474    -271.877     160.888
==============================================================================
Omnibus:                        1.440   Durbin-Watson:                   2.502
Prob(Omnibus):                  0.487   Jarque-Bera (JB):                0.925
Skew:                          -0.459   Prob(JB):                        0.630
Kurtosis:                       1.826   Cond. No.                         43.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [30]:
X = df_pax_800.iloc[:,[5,6,7,8,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_800['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_800 = df_pax_800.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       0.961
Model:                                  OLS   Adj. R-squared:                  0.825
Method:                       Least Squares   F-statistic:                     7.065
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):              0.130
Time:                              15:20:38   Log-Likelihood:                -21.373
No. Observations:                        10   AIC:                             58.75
Df Residuals:                             2   BIC:                             61.17
Df Model:                                 7
Covariance Type:                  nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings     -5.5903      9.431     -0.593      0.613     -46.170      34.990
#students from faculties   -161.3591     38.106     -4.234      0.052    -325.318       2.600
#lecturers from faculties   -89.0498     27.503     -3.238      0.084    -207.386      29.287
faculty area                298.0215     63.711      4.678      0.043      23.895     572.148
#offices                   -100.9419     27.059     -3.730      0.065    -217.365      15.482
#dorms                       68.2812     24.209      2.820      0.106     -35.883     172.445
#waiting seats              -72.9764     23.729     -3.075      0.091    -175.076      29.123
const                        39.7390     12.306      3.229      0.084     -13.208      92.686
==============================================================================
Omnibus:                        2.484   Durbin-Watson:                   1.954
Prob(Omnibus):                  0.289   Jarque-Bera (JB):                1.422
Skew:                          -0.891   Prob(JB):                        0.491
Kurtosis:                       2.515   Cond. No.                         101.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [31]:
df_pax_800

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances,predict_waiting_passengers,predict_departing_passengers,predict_arriving_passengers
0,พหล,8:00-8:30,175,145,18,0.037671,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667,143.614067,126.214202,22.196454
5,สระน้ำ พหล,8:00-8:30,58,97,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333,51.923106,104.171252,1.485865
10,งาม1,8:00-8:30,71,9,25,0.083752,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667,80.982961,-0.722037,23.127771
15,งาม3,8:00-8:30,18,7,2,0.145478,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000,62.409510,27.636914,2.308678
20,วิภา,8:00-8:30,35,2,24,0.161393,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333,45.371850,13.609534,21.883935
25,ศร.1,8:00-8:30,5,7,20,0.864445,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667,-15.037516,-8.117838,18.768876
30,หอสมุด,8:00-8:30,2,8,26,0.007676,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000,1.884505,5.809039,26.144464
35,บาร์ใหม่,8:00-8:30,3,6,2,0.789811,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000,-17.470497,-1.614621,5.057216
40,อาคารจักร,8:00-8:30,0,0,14,0.849092,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000,8.027466,25.440182,12.344186
45,RDIPT,8:00-8:30,4,1,32,0.512451,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000,9.294550,-10.426627,32.682554

In [32]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_800['#waiting passengers (y)'], df_pax_800['predict_waiting_passengers']))
RMSE_waiting_passengers

20.284165889547864

In [33]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_800['#departing passengers (y)'], df_pax_800['predict_departing_passengers']))
RMSE_departing_passengers

14.589780637257853

In [34]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_800['#arriving passengers (y)'], df_pax_800['predict_arriving_passengers']))
RMSE_arriving_passengers

2.051141054813302

## 8:30 - 9:00

In [35]:
df_pax_830 = df_pax[df_pax['time'] == '8:30-9:00'].copy()
df_pax_830

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
1,พหล,8:30-9:00,126,110,22,0.000167,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
6,สระน้ำ พหล,8:30-9:00,18,89,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
11,งาม1,8:30-9:00,111,21,26,0.059508,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
16,งาม3,8:30-9:00,8,1,4,0.063658,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
21,วิภา,8:30-9:00,81,54,23,0.030519,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
26,ศร.1,8:30-9:00,1,4,15,0.247519,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
31,หอสมุด,8:30-9:00,0,4,33,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
36,บาร์ใหม่,8:30-9:00,0,0,3,0.230718,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
41,อาคารจักร,8:30-9:00,0,0,30,0.200150,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
46,RDIPT,8:30-9:00,0,3,19,0.156151,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [36]:
X = df_pax_830.iloc[:,[7,8,9,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_830['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_830 = df_pax_830.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       0.880
Model:                                 OLS   Adj. R-squared:                  0.641
Method:                      Least Squares   F-statistic:                     3.683
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):              0.156
Time:                             15:20:38   Log-Likelihood:                -42.325
No. Observations:                       10   AIC:                             98.65
Df Residuals:                            3   BIC:                             100.8
Df Model:                                6
Covariance Type:                 nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#lecturers from faculties  -243.3775    107.522     -2.264      0.109    -585.560      98.805
faculty area                241.0313    150.928      1.597      0.209    -239.289     721.352
#stores                    -303.0612    112.357     -2.697      0.074    -660.632      54.509
#offices                    318.4765    158.751      2.006      0.139    -186.742     823.694
#dorms                      196.6991    112.122      1.754      0.178    -160.124     553.522
#waiting seats              240.3431     92.199      2.607      0.080     -53.077     533.763
const                      -121.7673     74.545     -1.633      0.201    -359.001     115.467
==============================================================================
Omnibus:                        6.394   Durbin-Watson:                   2.499
Prob(Omnibus):                  0.041   Jarque-Bera (JB):                2.269
Skew:                          -1.045   Prob(JB):                        0.322
Kurtosis:                       4.038   Cond. No.                         36.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))

In [37]:
X = df_pax_830.iloc[:,[5,7,9,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_830['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_830 = df_pax_830.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       0.932
Model:                                   OLS   Adj. R-squared:                  0.797
Method:                        Least Squares   F-statistic:                     6.897
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):             0.0708
Time:                               15:20:38   Log-Likelihood:                -37.364
No. Observations:                         10   AIC:                             88.73
Df Residuals:                              3   BIC:                             90.85
Df Model:                                  6
Covariance Type:                   nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings    676.6024    279.388      2.422      0.094    -212.534    1565.739
#lecturers from faculties  -199.4472     58.030     -3.437      0.041    -384.124     -14.770
#stores                    -383.0477    120.169     -3.188      0.050    -765.480      -0.616
#offices                    352.9937    132.864      2.657      0.077     -69.838     775.825
#dorms                      389.3818    139.556      2.790      0.068     -54.749     833.512
#waiting seats              176.7104     71.337      2.477      0.089     -50.316     403.737
const                       -53.4774     57.016     -0.938      0.417    -234.927     127.972
==============================================================================
Omnibus:                        3.926   Durbin-Watson:                   2.548
Prob(Omnibus):                  0.140   Jarque-Bera (JB):                1.666
Skew:                          -0.999   Prob(JB):                        0.435
Kurtosis:                       3.101   Cond. No.                         85.9
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [38]:
X = df_pax_830.iloc[:,[5,6,7,8,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_830['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_830 = df_pax_830.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       0.918
Model:                                  OLS   Adj. R-squared:                  0.633
Method:                       Least Squares   F-statistic:                     3.218
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):              0.257
Time:                              15:20:38   Log-Likelihood:                -25.425
No. Observations:                        10   AIC:                             66.85
Df Residuals:                             2   BIC:                             69.27
Df Model:                                 7
Covariance Type:                  nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings    -76.1810     59.962     -1.270      0.332    -334.179     181.817
#students from faculties   -112.8489     59.778     -1.888      0.200    -370.051     144.353
#lecturers from faculties   -23.9159     39.120     -0.611      0.603    -192.235     144.403
faculty area                161.5509     94.670      1.706      0.230    -245.779     568.881
#offices                     -4.6782     38.068     -0.123      0.913    -168.469     159.113
#dorms                       54.7985     38.568      1.421      0.291    -111.145     220.742
#waiting seats              -12.4437     34.527     -0.360      0.753    -161.000     136.112
const                         1.2179     17.458      0.070      0.951     -73.897      76.333
==============================================================================
Omnibus:                        0.422   Durbin-Watson:                   2.579
Prob(Omnibus):                  0.810   Jarque-Bera (JB):                0.469
Skew:                          -0.040   Prob(JB):                        0.791
Kurtosis:                       1.942   Cond. No.                         99.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [39]:
df_pax_830

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances,predict_waiting_passengers,predict_departing_passengers,predict_arriving_passengers
1,พหล,8:30-9:00,126,110,22,0.000167,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667,126.182729,110.411959,26.132321
6,สระน้ำ พหล,8:30-9:00,18,89,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333,5.528127,80.732232,-0.786647
11,งาม1,8:30-9:00,111,21,26,0.059508,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667,85.314328,10.573616,20.760533
16,งาม3,8:30-9:00,8,1,4,0.063658,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000,48.142854,23.896983,8.736884
21,วิภา,8:30-9:00,81,54,23,0.030519,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333,80.445434,51.973901,21.020309
26,ศร.1,8:30-9:00,1,4,15,0.247519,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667,-0.983754,-6.924851,14.667980
31,หอสมุด,8:30-9:00,0,4,33,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000,0.343433,3.769894,33.214668
36,บาร์ใหม่,8:30-9:00,0,0,3,0.230718,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000,-6.720639,12.027638,3.927861
41,อาคารจักร,8:30-9:00,0,0,30,0.200150,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000,-8.442869,-6.949235,27.435433
46,RDIPT,8:30-9:00,0,3,19,0.156151,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000,15.190356,6.487863,21.890657

In [40]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_830['#waiting passengers (y)'], df_pax_830['predict_waiting_passengers']))
RMSE_waiting_passengers

16.668353860655248

In [41]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_830['#departing passengers (y)'], df_pax_830['predict_departing_passengers']))
RMSE_departing_passengers

10.149574045458696

In [42]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_830['#arriving passengers (y)'], df_pax_830['predict_arriving_passengers']))
RMSE_arriving_passengers

3.075725820528663

## 9:00 - 9:30

In [43]:
df_pax_900 = df_pax[df_pax['time'] == '9:00-9:30'].copy()
df_pax_900

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
2,พหล,9:00-9:30,99,90,24,0.042237,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
7,สระน้ำ พหล,9:00-9:30,16,39,1,0.029770,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
12,งาม1,9:00-9:30,66,41,26,0.531290,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
17,งาม3,9:00-9:30,0,1,3,0.524621,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
22,วิภา,9:00-9:30,75,50,22,0.059539,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
27,ศร.1,9:00-9:30,1,7,14,0.870062,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
32,หอสมุด,9:00-9:30,2,0,13,0.003745,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
37,บาร์ใหม่,9:00-9:30,1,2,4,0.735519,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
42,อาคารจักร,9:00-9:30,3,3,24,0.461711,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
47,RDIPT,9:00-9:30,10,13,22,0.250328,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [44]:
X = df_pax_900.iloc[:,[7,8,9,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_900['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_900 = df_pax_900.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       0.897
Model:                                 OLS   Adj. R-squared:                  0.692
Method:                      Least Squares   F-statistic:                     4.374
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):              0.127
Time:                             15:20:39   Log-Likelihood:                -38.538
No. Observations:                       10   AIC:                             91.08
Df Residuals:                            3   BIC:                             93.19
Df Model:                                6
Covariance Type:                 nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#lecturers from faculties  -127.1396     73.629     -1.727      0.183    -361.460     107.180
faculty area                124.5396    103.353      1.205      0.315    -204.375     453.454
#stores                    -196.6899     76.940     -2.556      0.083    -441.547      48.167
#offices                    218.0576    108.710      2.006      0.139    -127.906     564.021
#dorms                       98.7765     76.779      1.287      0.289    -145.569     343.122
#waiting seats              188.3302     63.136      2.983      0.058     -12.598     389.258
const                       -81.2382     51.047     -1.591      0.210    -243.691      81.215
==============================================================================
Omnibus:                       14.550   Durbin-Watson:                   2.213
Prob(Omnibus):                  0.001   Jarque-Bera (JB):                7.347
Skew:                          -1.763   Prob(JB):                       0.0254
Kurtosis:                       5.281   Cond. No.                         36.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))

In [45]:
X = df_pax_900.iloc[:,[5,7,9,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_900['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_900 = df_pax_900.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       0.822
Model:                                   OLS   Adj. R-squared:                  0.467
Method:                        Least Squares   F-statistic:                     2.315
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):              0.262
Time:                               15:20:39   Log-Likelihood:                -38.960
No. Observations:                         10   AIC:                             91.92
Df Residuals:                              3   BIC:                             94.04
Df Model:                                  6
Covariance Type:                   nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings      0.1381    106.318      0.001      0.999    -338.213     338.489
#lecturers from faculties   -44.4325     29.475     -1.507      0.229    -138.235      49.370
#stores                    -127.7208    152.736     -0.836      0.464    -613.794     358.352
#offices                    174.2027    125.370      1.390      0.259    -224.780     573.185
#dorms                       66.7918    130.091      0.513      0.643    -347.215     480.798
#waiting seats              121.5784     79.914      1.521      0.226    -132.743     375.899
const                       -32.2920     63.654     -0.507      0.647    -234.868     170.284
==============================================================================
Omnibus:                        7.658   Durbin-Watson:                   1.924
Prob(Omnibus):                  0.022   Jarque-Bera (JB):                2.945
Skew:                          -1.187   Prob(JB):                        0.229
Kurtosis:                       4.197   Cond. No.                         55.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [46]:
X = df_pax_900.iloc[:,[5,6,7,8,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_900['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_900 = df_pax_900.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       0.911
Model:                                  OLS   Adj. R-squared:                  0.599
Method:                       Least Squares   F-statistic:                     2.922
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):              0.279
Time:                              15:20:39   Log-Likelihood:                -24.288
No. Observations:                        10   AIC:                             64.58
Df Residuals:                             2   BIC:                             67.00
Df Model:                                 7
Covariance Type:                  nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings    -38.7294     39.036     -0.992      0.426    -206.689     129.231
#students from faculties    -66.3502     94.090     -0.705      0.554    -471.187     338.487
#lecturers from faculties   -53.5812     31.264     -1.714      0.229    -188.101      80.939
faculty area                150.3040    107.400      1.399      0.297    -311.799     612.407
#offices                     -3.4194     48.044     -0.071      0.950    -210.134     203.295
#dorms                       16.5599     50.454      0.328      0.774    -200.526     233.646
#waiting seats               -4.1433     42.679     -0.097      0.932    -187.778     179.491
const                         1.5616     20.464      0.076      0.946     -86.490      89.613
==============================================================================
Omnibus:                        1.328   Durbin-Watson:                   2.581
Prob(Omnibus):                  0.515   Jarque-Bera (JB):                0.560
Skew:                           0.565   Prob(JB):                        0.756
Kurtosis:                       2.741   Cond. No.                         142.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [47]:
df_pax_900

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances,predict_waiting_passengers,predict_departing_passengers,predict_arriving_passengers
2,พหล,9:00-9:30,99,90,24,0.042237,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667,93.065362,76.026015,26.632434
7,สระน้ำ พหล,9:00-9:30,16,39,1,0.029770,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333,7.872467,35.775848,-0.866018
12,งาม1,9:00-9:30,66,41,26,0.531290,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667,54.708943,34.796603,20.156132
17,งาม3,9:00-9:30,0,1,3,0.524621,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000,30.518129,30.479858,6.994964
22,วิภา,9:00-9:30,75,50,22,0.059539,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333,76.370173,55.590009,21.064021
27,ศร.1,9:00-9:30,1,7,14,0.870062,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667,-6.510838,-7.550651,15.473349
32,หอสมุด,9:00-9:30,2,0,13,0.003745,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000,2.024196,-0.816734,13.080315
37,บาร์ใหม่,9:00-9:30,1,2,4,0.735519,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000,-2.583910,-1.250233,4.191913
42,อาคารจักร,9:00-9:30,3,3,24,0.461711,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000,-0.268069,10.084097,21.716789
47,RDIPT,9:00-9:30,10,13,22,0.250328,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000,17.803548,12.865189,24.556099

In [48]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_900['#waiting passengers (y)'], df_pax_900['predict_waiting_passengers']))
RMSE_waiting_passengers

11.41416489390661

In [49]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_900['#departing passengers (y)'], df_pax_900['predict_departing_passengers']))
RMSE_departing_passengers

11.906363415046803

In [50]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_900['#arriving passengers (y)'], df_pax_900['predict_arriving_passengers']))
RMSE_arriving_passengers

2.7451603642689446

## 9:30 - 10:00

In [51]:
df_pax_930 = df_pax[df_pax['time'] == '9:30-10:00'].copy()
df_pax_930

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
3,พหล,9:30-10:00,79,74,26,0.075226,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
8,สระน้ำ พหล,9:30-10:00,17,58,8,0.040629,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
13,งาม1,9:30-10:00,34,19,33,0.165810,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
18,งาม3,9:30-10:00,0,0,4,0.138925,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
23,วิภา,9:30-10:00,32,18,12,0.275978,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
28,ศร.1,9:30-10:00,4,5,5,1.000000,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
33,หอสมุด,9:30-10:00,1,10,20,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
38,บาร์ใหม่,9:30-10:00,0,0,5,0.795138,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
43,อาคารจักร,9:30-10:00,3,4,26,0.962741,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
48,RDIPT,9:30-10:00,0,5,17,0.761281,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [52]:
X = df_pax_930.iloc[:,[7,8,9,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_930['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_930 = df_pax_930.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       0.831
Model:                                 OLS   Adj. R-squared:                  0.492
Method:                      Least Squares   F-statistic:                     2.453
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):              0.247
Time:                             15:20:39   Log-Likelihood:                -37.164
No. Observations:                       10   AIC:                             88.33
Df Residuals:                            3   BIC:                             90.45
Df Model:                                6
Covariance Type:                 nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#lecturers from faculties   -79.7315     64.179     -1.242      0.302    -283.977     124.514
faculty area                 50.4519     90.088      0.560      0.615    -236.248     337.151
#stores                    -151.4507     67.065     -2.258      0.109    -364.881      61.980
#offices                    200.2845     94.757      2.114      0.125    -101.276     501.845
#dorms                      108.4021     66.925      1.620      0.204    -104.583     321.387
#waiting seats              129.8224     55.033      2.359      0.099     -45.317     304.962
const                       -65.1904     44.495     -1.465      0.239    -206.793      76.413
==============================================================================
Omnibus:                        7.556   Durbin-Watson:                   1.553
Prob(Omnibus):                  0.023   Jarque-Bera (JB):                2.853
Skew:                          -1.151   Prob(JB):                        0.240
Kurtosis:                       4.243   Cond. No.                         36.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))

In [53]:
X = df_pax_930.iloc[:,[5,7,9,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_930['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_930 = df_pax_930.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       0.913
Model:                                   OLS   Adj. R-squared:                  0.740
Method:                        Least Squares   F-statistic:                     5.261
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):              0.101
Time:                               15:20:39   Log-Likelihood:                -33.924
No. Observations:                         10   AIC:                             81.85
Df Residuals:                              3   BIC:                             83.97
Df Model:                                  6
Covariance Type:                   nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings     80.1685     34.285      2.338      0.101     -28.942     189.279
#lecturers from faculties  -126.0006     37.125     -3.394      0.043    -244.149      -7.853
#stores                    -211.4824     59.919     -3.529      0.039    -402.171     -20.794
#offices                    213.6374     77.560      2.754      0.070     -33.192     460.467
#dorms                      252.1310     77.992      3.233      0.048       3.926     500.336
#waiting seats               72.3485     40.743      1.776      0.174     -57.314     202.011
const                       -23.1778     34.834     -0.665      0.553    -134.034      87.678
==============================================================================
Omnibus:                        1.629   Durbin-Watson:                   2.599
Prob(Omnibus):                  0.443   Jarque-Bera (JB):                0.480
Skew:                          -0.537   Prob(JB):                        0.786
Kurtosis:                       2.984   Cond. No.                         47.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [54]:
X = df_pax_930.iloc[:,[5,6,7,8,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_930['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_930 = df_pax_930.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       0.791
Model:                                  OLS   Adj. R-squared:                  0.061
Method:                       Least Squares   F-statistic:                     1.083
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):              0.559
Time:                              15:20:39   Log-Likelihood:                -29.232
No. Observations:                        10   AIC:                             74.46
Df Residuals:                             2   BIC:                             76.88
Df Model:                                 7
Covariance Type:                  nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings    -34.1963     19.034     -1.797      0.214    -116.093      47.700
#students from faculties   -127.5292     79.209     -1.610      0.249    -468.340     213.281
#lecturers from faculties   -12.3105     55.922     -0.220      0.846    -252.925     228.304
faculty area                171.4880    131.278      1.306      0.321    -393.356     736.332
#offices                     -8.5945     53.731     -0.160      0.888    -239.779     222.590
#dorms                       41.8351     50.872      0.822      0.497    -177.049     260.720
#waiting seats              -26.6947     48.168     -0.554      0.635    -233.943     180.554
const                        11.0820     24.492      0.452      0.695     -94.300     116.464
==============================================================================
Omnibus:                        1.146   Durbin-Watson:                   2.480
Prob(Omnibus):                  0.564   Jarque-Bera (JB):                0.280
Skew:                          -0.408   Prob(JB):                        0.869
Kurtosis:                       2.925   Cond. No.                         94.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [55]:
df_pax_930

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances,predict_waiting_passengers,predict_departing_passengers,predict_arriving_passengers
3,พหล,9:30-10:00,79,74,26,0.075226,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667,65.892305,68.918696,27.381538
8,สระน้ำ พหล,9:30-10:00,17,58,8,0.040629,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333,12.469624,57.979141,4.821764
13,งาม1,9:30-10:00,34,19,33,0.165810,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667,34.886115,7.340357,25.220959
18,งาม3,9:30-10:00,0,0,4,0.138925,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000,24.682293,15.378256,13.311002
23,วิภา,9:30-10:00,32,18,12,0.275978,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333,36.027859,21.865718,11.538030
28,ศร.1,9:30-10:00,4,5,5,1.000000,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667,-6.522867,2.239287,6.514946
33,หอสมุด,9:30-10:00,1,10,20,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000,0.902734,9.390143,20.193554
38,บาร์ใหม่,9:30-10:00,0,0,5,0.795138,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000,-6.710347,-6.786386,1.683503
43,อาคารจักร,9:30-10:00,3,4,26,0.962741,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000,4.942660,11.084527,23.487169
48,RDIPT,9:30-10:00,0,5,17,0.761281,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000,3.429623,5.590262,21.847535

In [56]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_930['#waiting passengers (y)'], df_pax_930['predict_waiting_passengers']))
RMSE_waiting_passengers

9.949198928276594

In [57]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_930['#departing passengers (y)'], df_pax_930['predict_departing_passengers']))
RMSE_departing_passengers

7.195758028149781

In [58]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_930['#arriving passengers (y)'], df_pax_930['predict_arriving_passengers']))
RMSE_arriving_passengers

4.500845126299057

## 10:00 - 10:30

In [59]:
df_pax_1000 = df_pax[df_pax['time'] == '10:00-10:30'].copy()
df_pax_1000

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
4,พหล,10:00-10:30,42,42,15,0.046459,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
9,สระน้ำ พหล,10:00-10:30,18,50,16,0.023591,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
14,งาม1,10:00-10:30,42,15,8,0.107763,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
19,งาม3,10:00-10:30,0,0,3,0.080509,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
24,วิภา,10:00-10:30,23,10,9,0.045684,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
29,ศร.1,10:00-10:30,0,3,6,0.363228,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
34,หอสมุด,10:00-10:30,2,10,6,0.014042,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
39,บาร์ใหม่,10:00-10:30,2,0,0,0.225119,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
44,อาคารจักร,10:00-10:30,2,1,9,0.419023,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
49,RDIPT,10:00-10:30,7,3,17,0.356488,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [60]:
X = df_pax_1000.iloc[:,[7,8,9,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_1000['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_1000 = df_pax_1000.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       0.784
Model:                                 OLS   Adj. R-squared:                  0.353
Method:                      Least Squares   F-statistic:                     1.817
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):              0.334
Time:                             15:20:39   Log-Likelihood:                -34.204
No. Observations:                       10   AIC:                             82.41
Df Residuals:                            3   BIC:                             84.53
Df Model:                                6
Covariance Type:                 nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#lecturers from faculties   -82.2192     47.735     -1.722      0.183    -234.135      69.696
faculty area                 87.6184     67.006      1.308      0.282    -125.625     300.862
#stores                    -107.4092     49.882     -2.153      0.120    -266.156      51.338
#offices                     85.0059     70.479      1.206      0.314    -139.291     309.303
#dorms                       71.5671     49.778      1.438      0.246     -86.848     229.983
#waiting seats               55.6351     40.933      1.359      0.267     -74.632     185.902
const                       -21.0055     33.095     -0.635      0.571    -126.328      84.317
==============================================================================
Omnibus:                        6.242   Durbin-Watson:                   2.542
Prob(Omnibus):                  0.044   Jarque-Bera (JB):                2.165
Skew:                          -1.010   Prob(JB):                        0.339
Kurtosis:                       4.056   Cond. No.                         36.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))

In [61]:
X = df_pax_1000.iloc[:,[5,7,9,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_1000['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_1000 = df_pax_1000.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       0.851
Model:                                   OLS   Adj. R-squared:                  0.553
Method:                        Least Squares   F-statistic:                     2.857
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):              0.209
Time:                               15:20:39   Log-Likelihood:                -33.038
No. Observations:                         10   AIC:                             80.08
Df Residuals:                              3   BIC:                             82.20
Df Model:                                  6
Covariance Type:                   nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings     93.5230     84.238      1.110      0.348    -174.559     361.605
#lecturers from faculties   -69.3098     35.259     -1.966      0.144    -181.521      42.901
#stores                     -72.7701     41.476     -1.754      0.178    -204.767      59.226
#offices                     45.8091     60.757      0.754      0.506    -147.545     239.163
#dorms                      100.8442     53.974      1.868      0.159     -70.926     272.615
#waiting seats               -1.0869     35.465     -0.031      0.977    -113.952     111.778
const                        28.8097     29.516      0.976      0.401     -65.122     122.742
==============================================================================
Omnibus:                        7.210   Durbin-Watson:                   1.948
Prob(Omnibus):                  0.027   Jarque-Bera (JB):                2.785
Skew:                          -1.188   Prob(JB):                        0.248
Kurtosis:                       4.019   Cond. No.                         40.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [62]:
X = df_pax_1000.iloc[:,[5,6,7,8,11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_1000['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_1000 = df_pax_1000.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       0.999
Model:                                  OLS   Adj. R-squared:                  0.994
Method:                       Least Squares   F-statistic:                     199.5
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):            0.00500
Time:                              15:20:39   Log-Likelihood:                 1.8124
No. Observations:                        10   AIC:                             12.38
Df Residuals:                             2   BIC:                             14.80
Df Model:                                 7
Covariance Type:                  nonrobust
=============================================================================================
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
#students from buildings      2.2680      3.372      0.673      0.570     -12.240      16.776
#students from faculties    -89.5124      3.864    -23.163      0.002    -106.140     -72.885
#lecturers from faculties   -31.9760      2.391    -13.374      0.006     -42.264     -21.688
faculty area                124.8586      6.158     20.275      0.002      98.362     151.355
#offices                    -48.2364      2.320    -20.793      0.002     -58.218     -38.255
#dorms                       38.7401      2.105     18.408      0.003      29.685      47.795
#waiting seats              -50.8631      2.137    -23.797      0.002     -60.059     -41.667
const                        35.7550      1.048     34.102      0.001      31.244      40.266
==============================================================================
Omnibus:                        2.318   Durbin-Watson:                   1.631
Prob(Omnibus):                  0.314   Jarque-Bera (JB):                1.364
Skew:                          -0.865   Prob(JB):                        0.506
Kurtosis:                       2.468   Cond. No.                         92.9
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [63]:
df_pax_1000

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances,predict_waiting_passengers,predict_departing_passengers,predict_arriving_passengers
4,พหล,10:00-10:30,42,42,15,0.046459,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667,42.431056,36.631292,15.351306
9,สระน้ำ พหล,10:00-10:30,18,50,16,0.023591,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333,12.355645,46.649223,15.971283
14,งาม1,10:00-10:30,42,15,8,0.107763,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667,30.379530,10.043702,7.783375
19,งาม3,10:00-10:30,0,0,3,0.080509,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000,17.797154,16.131439,2.783543
24,วิภา,10:00-10:30,23,10,9,0.045684,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333,22.560036,12.092956,8.859386
29,ศร.1,10:00-10:30,0,3,6,0.363228,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667,-1.262636,1.447416,6.057076
34,หอสมุด,10:00-10:30,2,10,6,0.014042,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000,2.125762,10.136411,5.998022
39,บาร์ใหม่,10:00-10:30,2,0,0,0.225119,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000,0.075447,-8.622011,0.378154
44,อาคารจักร,10:00-10:30,2,1,9,0.419023,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000,-1.978215,1.228273,8.850476
49,RDIPT,10:00-10:30,7,3,17,0.356488,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000,13.516221,8.261299,16.967378

In [64]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_1000['#waiting passengers (y)'], df_pax_1000['predict_waiting_passengers']))
RMSE_waiting_passengers

7.400090641091393

In [65]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_1000['#departing passengers (y)'], df_pax_1000['predict_departing_passengers']))
RMSE_departing_passengers

6.585749577591458

In [66]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_1000['#arriving passengers (y)'], df_pax_1000['predict_arriving_passengers']))
RMSE_arriving_passengers

0.20186036330498508

# 2.1.iii Regression from some feature set classify by location and time

In [67]:
df_pax

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,พหล,8:00-8:30,175,145,18,0.037671,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
1,พหล,8:30-9:00,126,110,22,0.000167,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
2,พหล,9:00-9:30,99,90,24,0.042237,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
3,พหล,9:30-10:00,79,74,26,0.075226,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
4,พหล,10:00-10:30,42,42,15,0.046459,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
5,สระน้ำ พหล,8:00-8:30,58,97,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
6,สระน้ำ พหล,8:30-9:00,18,89,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
7,สระน้ำ พหล,9:00-9:30,16,39,1,0.029770,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
8,สระน้ำ พหล,9:30-10:00,17,58,8,0.040629,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
9,สระน้ำ พหล,10:00-10:30,18,50,16,0.023591,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
10,งาม1,8:00-8:30,71,9,25,0.083752,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
11,งาม1,8:30-9:00,111,21,26,0.059508,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
12,งาม1,9:00-9:30,66,41,26,0.531290,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
13,งาม1,9:30-10:00,34,19,33,0.165810,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
14,งาม1,10:00-10:30,42,15,8,0.107763,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
15,งาม3,8:00-8:30,18,7,2,0.145478,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
16,งาม3,8:30-9:00,8,1,4,0.063658,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
17,งาม3,9:00-9:30,0,1,3,0.524621,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
18,งาม3,9:30-10:00,0,0,4,0.138925,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
19,งาม3,10:00-10:30,0,0,3,0.080509,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
20,วิภา,8:00-8:30,35,2,24,0.161393,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
21,วิภา,8:30-9:00,81,54,23,0.030519,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
22,วิภา,9:00-9:30,75,50,22,0.059539,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
23,วิภา,9:30-10:00,32,18,12,0.275978,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
24,วิภา,10:00-10:30,23,10,9,0.045684,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
25,ศร.1,8:00-8:30,5,7,20,0.864445,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
26,ศร.1,8:30-9:00,1,4,15,0.247519,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
27,ศร.1,9:00-9:30,1,7,14,0.870062,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
28,ศร.1,9:30-10:00,4,5,5,1.000000,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
29,ศร.1,10:00-10:30,0,3,6,0.363228,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
30,หอสมุด,8:00-8:30,2,8,26,0.007676,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
31,หอสมุด,8:30-9:00,0,4,33,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
32,หอสมุด,9:00-9:30,2,0,13,0.003745,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
33,หอสมุด,9:30-10:00,1,10,20,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
34,หอสมุด,10:00-10:30,2,10,6,0.014042,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
35,บาร์ใหม่,8:00-8:30,3,6,2,0.789811,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
36,บาร์ใหม่,8:30-9:00,0,0,3,0.230718,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
37,บาร์ใหม่,9:00-9:30,1,2,4,0.735519,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
38,บาร์ใหม่,9:30-10:00,0,0,5,0.795138,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
39,บาร์ใหม่,10:00-10:30,2,0,0,0.225119,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
40,อาคารจักร,8:00-8:30,0,0,14,0.849092,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
41,อาคารจักร,8:30-9:00,0,0,30,0.200150,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
42,อาคารจักร,9:00-9:30,3,3,24,0.461711,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
43,อาคารจักร,9:30-10:00,3,4,26,0.962741,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
44,อาคารจักร,10:00-10:30,2,1,9,0.419023,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
45,RDIPT,8:00-8:30,4,1,32,0.512451,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
46,RDIPT,8:30-9:00,0,3,19,0.156151,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
47,RDIPT,9:00-9:30,10,13,22,0.250328,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
48,RDIPT,9:30-10:00,0,5,17,0.761281,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
49,RDIPT,10:00-10:30,7,3,17,0.356488,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

## Predict by the gate

In [68]:
df_pax_gate = df_pax[(df_pax['location'] == 'พหล') | (df_pax['location'] == 'สระน้ำ พหล') | (df_pax['location'] == 'งาม1') | (df_pax['location'] == 'งาม3') | (df_pax['location'] == 'วิภา')]
df_pax_gate

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,พหล,8:00-8:30,175,145,18,0.037671,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
1,พหล,8:30-9:00,126,110,22,0.000167,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
2,พหล,9:00-9:30,99,90,24,0.042237,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
3,พหล,9:30-10:00,79,74,26,0.075226,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
4,พหล,10:00-10:30,42,42,15,0.046459,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
5,สระน้ำ พหล,8:00-8:30,58,97,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
6,สระน้ำ พหล,8:30-9:00,18,89,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
7,สระน้ำ พหล,9:00-9:30,16,39,1,0.029770,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
8,สระน้ำ พหล,9:30-10:00,17,58,8,0.040629,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
9,สระน้ำ พหล,10:00-10:30,18,50,16,0.023591,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
10,งาม1,8:00-8:30,71,9,25,0.083752,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
11,งาม1,8:30-9:00,111,21,26,0.059508,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
12,งาม1,9:00-9:30,66,41,26,0.531290,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
13,งาม1,9:30-10:00,34,19,33,0.165810,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
14,งาม1,10:00-10:30,42,15,8,0.107763,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
15,งาม3,8:00-8:30,18,7,2,0.145478,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
16,งาม3,8:30-9:00,8,1,4,0.063658,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
17,งาม3,9:00-9:30,0,1,3,0.524621,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
18,งาม3,9:30-10:00,0,0,4,0.138925,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
19,งาม3,10:00-10:30,0,0,3,0.080509,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
20,วิภา,8:00-8:30,35,2,24,0.161393,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
21,วิภา,8:30-9:00,81,54,23,0.030519,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
22,วิภา,9:00-9:30,75,50,22,0.059539,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
23,วิภา,9:30-10:00,32,18,12,0.275978,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
24,วิภา,10:00-10:30,23,10,9,0.045684,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333

## 8:00 - 8:30

In [69]:
df_pax_gate_800 = df_pax_gate[df_pax_gate['time'] == '8:00-8:30'].copy()
df_pax_gate_800

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,พหล,8:00-8:30,175,145,18,0.037671,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
5,สระน้ำ พหล,8:00-8:30,58,97,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
10,งาม1,8:00-8:30,71,9,25,0.083752,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
15,งาม3,8:00-8:30,18,7,2,0.145478,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
20,วิภา,8:00-8:30,35,2,24,0.161393,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333

In [70]:
X = df_pax_gate_800.iloc[:,[5,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_800['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_800 = df_pax_gate_800.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       0.922
Model:                                 OLS   Adj. R-squared:                  0.689
Method:                      Least Squares   F-statistic:                     3.953
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):              0.350
Time:                             15:20:39   Log-Likelihood:                -20.741
No. Observations:                        5   AIC:                             49.48
Df Residuals:                            1   BIC:                             47.92
Df Model:                                3
Covariance Type:                 nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from buildings   973.1084    751.231      1.295      0.419   -8572.192    1.05e+04
#dorms                   -5037.5374   2091.682     -2.408      0.251   -3.16e+04    2.15e+04
#waiting seats             333.1374    121.397      2.744      0.222   -1209.355    1875.630
const                       94.6973     27.593      3.432      0.181    -255.911     445.306
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.486
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.377
Skew:                          -0.348   Prob(JB):                        0.828
Kurtosis:                       1.848   Cond. No.                         155.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [71]:
X = df_pax_gate_800.iloc[:,[9,11,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_800['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_800 = df_pax_gate_800.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       0.968
Model:                                   OLS   Adj. R-squared:                  0.873
Method:                        Least Squares   F-statistic:                     10.15
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):              0.226
Time:                               15:20:39   Log-Likelihood:                -18.810
No. Observations:                          5   AIC:                             45.62
Df Residuals:                              1   BIC:                             44.06
Df Model:                                  3
Covariance Type:                   nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
#stores         -526.6394    107.271     -4.909      0.128   -1889.653     836.374
#offices         432.3414    134.634      3.211      0.192   -1278.341    2143.024
#waiting seats   197.8116     83.103      2.380      0.253    -858.108    1253.732
const            -57.0899     64.250     -0.889      0.538    -873.464     759.285
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.850
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.183
Skew:                          -0.285   Prob(JB):                        0.913
Kurtosis:                       2.255   Cond. No.                         22.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [72]:
X = df_pax_gate_800.iloc[:,[8,11,12]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_800['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_800 = df_pax_gate_800.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       0.965
Model:                                  OLS   Adj. R-squared:                  0.859
Method:                       Least Squares   F-statistic:                     9.150
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):              0.237
Time:                              15:20:39   Log-Likelihood:                -10.243
No. Observations:                         5   AIC:                             28.49
Df Residuals:                             1   BIC:                             26.92
Df Model:                                 3
Covariance Type:                  nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
faculty area    81.2283     16.611      4.890      0.128    -129.831     292.288
#offices       -84.9869     18.733     -4.537      0.138    -323.007     153.033
#dorms        -296.1220    103.383     -2.864      0.214   -1609.723    1017.479
const           35.6886      7.916      4.508      0.139     -64.895     136.273
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.838
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.766
Skew:                           0.936   Prob(JB):                        0.682
Kurtosis:                       2.583   Cond. No.                         65.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [73]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_gate_800['#waiting passengers (y)'], df_pax_gate_800['predict_waiting_passengers']))
RMSE_waiting_passengers

15.32004984689285

In [74]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_gate_800['#departing passengers (y)'], df_pax_gate_800['predict_departing_passengers']))
RMSE_departing_passengers

10.41262027043772

In [75]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_gate_800['#arriving passengers (y)'], df_pax_gate_800['predict_arriving_passengers']))
RMSE_arriving_passengers

1.8770375361680256

## 8:30 - 9:00

In [76]:
df_pax_gate_830 = df_pax_gate[df_pax_gate['time'] == '8:30-9:00'].copy()
df_pax_gate_830

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
1,พหล,8:30-9:00,126,110,22,0.000167,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
6,สระน้ำ พหล,8:30-9:00,18,89,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
11,งาม1,8:30-9:00,111,21,26,0.059508,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
16,งาม3,8:30-9:00,8,1,4,0.063658,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
21,วิภา,8:30-9:00,81,54,23,0.030519,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333

In [77]:
X = df_pax_gate_830.iloc[:,[11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_830['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_830 = df_pax_gate_830.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       0.940
Model:                                 OLS   Adj. R-squared:                  0.761
Method:                      Least Squares   F-statistic:                     5.242
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):              0.308
Time:                             15:20:39   Log-Likelihood:                -19.399
No. Observations:                        5   AIC:                             46.80
Df Residuals:                            1   BIC:                             45.24
Df Model:                                3
Covariance Type:                 nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
#offices         195.1869     74.963      2.604      0.233    -757.305    1147.679
#dorms         -2016.6098    638.018     -3.161      0.195   -1.01e+04    6090.177
#waiting seats   349.1846     88.530      3.944      0.158    -775.699    1474.069
const            -54.2851     51.887     -1.046      0.486    -713.573     605.003
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.477
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.374
Skew:                           0.313   Prob(JB):                        0.829
Kurtosis:                       1.814   Cond. No.                         63.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [78]:
X = df_pax_gate_830.iloc[:,[9,11,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_830['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_830 = df_pax_gate_830.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       1.000
Model:                                   OLS   Adj. R-squared:                  1.000
Method:                        Least Squares   F-statistic:                     5902.
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):            0.00957
Time:                               15:20:40   Log-Likelihood:                -1.1628
No. Observations:                          5   AIC:                             10.33
Df Residuals:                              1   BIC:                             8.763
Df Model:                                  3
Covariance Type:                   nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
#stores         -321.1356      3.145   -102.094      0.006    -361.103    -281.168
#offices         207.4390      3.948     52.545      0.012     157.277     257.601
#waiting seats   127.0193      2.437     52.126      0.012      96.057     157.982
const             10.9029      1.884      5.787      0.109     -13.035      34.841
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.850
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.183
Skew:                          -0.285   Prob(JB):                        0.913
Kurtosis:                       2.255   Cond. No.                         22.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [79]:
X = df_pax_gate_830.iloc[:,[8,11,12]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_830['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_830 = df_pax_gate_830.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       0.884
Model:                                  OLS   Adj. R-squared:                  0.536
Method:                       Least Squares   F-statistic:                     2.543
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):              0.425
Time:                              15:20:40   Log-Likelihood:                -13.333
No. Observations:                         5   AIC:                             34.67
Df Residuals:                             1   BIC:                             33.10
Df Model:                                 3
Covariance Type:                  nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
faculty area    81.3876     30.818      2.641      0.230    -310.188     472.963
#offices       -81.8355     34.754     -2.355      0.256    -523.430     359.759
#dorms        -301.5370    191.804     -1.572      0.361   -2738.639    2135.566
const           35.4872     14.687      2.416      0.250    -151.125     222.099
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.838
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.766
Skew:                           0.936   Prob(JB):                        0.682
Kurtosis:                       2.583   Cond. No.                         65.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [80]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_gate_830['#waiting passengers (y)'], df_pax_gate_830['predict_waiting_passengers']))
RMSE_waiting_passengers

11.715443614039634

In [81]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_gate_830['#departing passengers (y)'], df_pax_gate_830['predict_departing_passengers']))
RMSE_departing_passengers

0.3053254762229565

In [82]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_gate_830['#arriving passengers (y)'], df_pax_gate_830['predict_arriving_passengers']))
RMSE_arriving_passengers

3.4824366448180806

## 9:00 - 9:30

In [83]:
df_pax_gate_900 = df_pax_gate[df_pax_gate['time'] == '9:00-9:30'].copy()
df_pax_gate_900

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
2,พหล,9:00-9:30,99,90,24,0.042237,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
7,สระน้ำ พหล,9:00-9:30,16,39,1,0.029770,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
12,งาม1,9:00-9:30,66,41,26,0.531290,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
17,งาม3,9:00-9:30,0,1,3,0.524621,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
22,วิภา,9:00-9:30,75,50,22,0.059539,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333

In [84]:
X = df_pax_gate_900.iloc[:,[11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_900['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_900 = df_pax_gate_900.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       0.985
Model:                                 OLS   Adj. R-squared:                  0.938
Method:                      Least Squares   F-statistic:                     21.24
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):              0.158
Time:                             15:20:40   Log-Likelihood:                -14.755
No. Observations:                        5   AIC:                             37.51
Df Residuals:                            1   BIC:                             35.95
Df Model:                                3
Covariance Type:                 nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
#offices         112.3879     29.612      3.795      0.164    -263.873     488.649
#dorms         -1497.4525    252.035     -5.941      0.106   -4699.862    1704.957
#waiting seats   262.1648     34.972      7.496      0.084    -182.196     706.526
const            -26.9025     20.497     -1.313      0.414    -287.340     233.535
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.477
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.374
Skew:                           0.313   Prob(JB):                        0.829
Kurtosis:                       1.814   Cond. No.                         63.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [85]:
X = df_pax_gate_900.iloc[:,[9,11,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_900['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_900 = df_pax_gate_900.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       0.950
Model:                                   OLS   Adj. R-squared:                  0.799
Method:                        Least Squares   F-statistic:                     6.293
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):              0.283
Time:                               15:20:40   Log-Likelihood:                -16.354
No. Observations:                          5   AIC:                             40.71
Df Residuals:                              1   BIC:                             39.15
Df Model:                                  3
Covariance Type:                   nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
#stores         -253.8560     65.639     -3.867      0.161   -1087.876     580.164
#offices         262.2861     82.382      3.184      0.194    -784.470    1309.042
#waiting seats   178.4396     50.850      3.509      0.177    -467.671     824.551
const            -62.8303     39.314     -1.598      0.356    -562.365     436.704
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.850
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.183
Skew:                           0.285   Prob(JB):                        0.913
Kurtosis:                       2.255   Cond. No.                         22.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [86]:
X = df_pax_gate_900.iloc[:,[8,11,12]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_900['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_900 = df_pax_gate_900.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       0.832
Model:                                  OLS   Adj. R-squared:                  0.329
Method:                       Least Squares   F-statistic:                     1.655
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):              0.506
Time:                              15:20:40   Log-Likelihood:                -14.560
No. Observations:                         5   AIC:                             37.12
Df Residuals:                             1   BIC:                             35.56
Df Model:                                 3
Covariance Type:                  nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
faculty area    85.2773     39.385      2.165      0.275    -415.156     585.711
#offices       -86.2132     44.416     -1.941      0.303    -650.571     478.145
#dorms        -335.8200    245.126     -1.370      0.401   -3450.438    2778.798
const           37.3590     18.770      1.990      0.296    -201.131     275.849
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.838
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.766
Skew:                           0.936   Prob(JB):                        0.682
Kurtosis:                       2.583   Cond. No.                         65.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [87]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_gate_900['#waiting passengers (y)'], df_pax_gate_900['predict_waiting_passengers']))
RMSE_waiting_passengers

4.627930583584687

In [88]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_gate_900['#departing passengers (y)'], df_pax_gate_900['predict_departing_passengers']))
RMSE_departing_passengers

6.371419875615518

In [89]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_gate_900['#arriving passengers (y)'], df_pax_gate_900['predict_arriving_passengers']))
RMSE_arriving_passengers

4.450554828408331

## 9:30 - 10:00

In [90]:
df_pax_gate_930 = df_pax_gate[df_pax_gate['time'] == '9:30-10:00'].copy()
df_pax_gate_930

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
3,พหล,9:30-10:00,79,74,26,0.075226,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
8,สระน้ำ พหล,9:30-10:00,17,58,8,0.040629,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
13,งาม1,9:30-10:00,34,19,33,0.165810,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
18,งาม3,9:30-10:00,0,0,4,0.138925,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
23,วิภา,9:30-10:00,32,18,12,0.275978,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333

In [91]:
X = df_pax_gate_930.iloc[:,[11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_930['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_930 = df_pax_gate_930.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       0.977
Model:                                 OLS   Adj. R-squared:                  0.907
Method:                      Least Squares   F-statistic:                     13.99
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):              0.194
Time:                             15:20:40   Log-Likelihood:                -14.044
No. Observations:                        5   AIC:                             36.09
Df Residuals:                            1   BIC:                             34.53
Df Model:                                3
Covariance Type:                 nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
#offices          68.5916     25.686      2.670      0.228    -257.786     394.969
#dorms         -1306.1468    218.621     -5.974      0.106   -4083.986    1471.692
#waiting seats   179.0222     30.335      5.901      0.107    -206.426     564.470
const             -4.4080     17.779     -0.248      0.845    -230.317     221.501
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.477
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.374
Skew:                          -0.313   Prob(JB):                        0.829
Kurtosis:                       1.814   Cond. No.                         63.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [92]:
X = df_pax_gate_930.iloc[:,[9,11,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_930['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_930 = df_pax_gate_930.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       0.998
Model:                                   OLS   Adj. R-squared:                  0.994
Method:                        Least Squares   F-statistic:                     207.4
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):             0.0510
Time:                               15:20:40   Log-Likelihood:                -7.5993
No. Observations:                          5   AIC:                             23.20
Df Residuals:                              1   BIC:                             21.64
Df Model:                                  3
Covariance Type:                   nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
#stores         -244.0499     11.396    -21.415      0.030    -388.852     -99.248
#offices         184.1388     14.303     12.874      0.049       2.402     365.876
#waiting seats    90.9770      8.829     10.305      0.062     -21.200     203.154
const             -9.3474      6.826     -1.369      0.402     -96.076      77.381
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.850
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.183
Skew:                           0.285   Prob(JB):                        0.913
Kurtosis:                       2.255   Cond. No.                         22.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [93]:
X = df_pax_gate_930.iloc[:,[8,11,12]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_930['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_930 = df_pax_gate_930.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       0.923
Model:                                  OLS   Adj. R-squared:                  0.690
Method:                       Least Squares   F-statistic:                     3.972
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):              0.350
Time:                              15:20:40   Log-Likelihood:                -12.714
No. Observations:                         5   AIC:                             33.43
Df Residuals:                             1   BIC:                             31.87
Df Model:                                 3
Covariance Type:                  nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
faculty area    87.7821     27.225      3.224      0.191    -258.147     433.711
#offices       -84.0383     30.703     -2.737      0.223    -474.156     306.079
#dorms        -501.8171    169.445     -2.962      0.207   -2654.824    1651.190
const           44.4516     12.975      3.426      0.181    -120.407     209.310
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.838
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.766
Skew:                           0.936   Prob(JB):                        0.682
Kurtosis:                       2.583   Cond. No.                         65.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [94]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_gate_930['#waiting passengers (y)'], df_pax_gate_930['predict_waiting_passengers']))
RMSE_waiting_passengers

4.014366862982059

In [95]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_gate_930['#departing passengers (y)'], df_pax_gate_930['predict_departing_passengers']))
RMSE_departing_passengers

1.1061998683102279

In [96]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_gate_930['#arriving passengers (y)'], df_pax_gate_930['predict_arriving_passengers']))
RMSE_arriving_passengers

3.076485614129462

## 10:00 - 10:30

In [97]:
df_pax_gate_1000 = df_pax_gate[df_pax_gate['time'] == '10:00-10:30'].copy()
df_pax_gate_1000

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
4,พหล,10:00-10:30,42,42,15,0.046459,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
9,สระน้ำ พหล,10:00-10:30,18,50,16,0.023591,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
14,งาม1,10:00-10:30,42,15,8,0.107763,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
19,งาม3,10:00-10:30,0,0,3,0.080509,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
24,วิภา,10:00-10:30,23,10,9,0.045684,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333

In [98]:
X = df_pax_gate_1000.iloc[:,[11,12,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_1000['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_1000 = df_pax_gate_1000.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       0.844
Model:                                 OLS   Adj. R-squared:                  0.376
Method:                      Least Squares   F-statistic:                     1.804
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):              0.489
Time:                             15:20:40   Log-Likelihood:                -16.264
No. Observations:                        5   AIC:                             40.53
Df Residuals:                            1   BIC:                             38.97
Df Model:                                3
Covariance Type:                 nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
#offices          45.7978     40.046      1.144      0.457    -463.034     554.630
#dorms          -758.5628    340.836     -2.226      0.269   -5089.297    3572.171
#waiting seats   100.5561     47.294      2.126      0.280    -500.369     701.481
const              2.2538     27.719      0.081      0.948    -349.945     354.453
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.477
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.374
Skew:                           0.313   Prob(JB):                        0.829
Kurtosis:                       1.814   Cond. No.                         63.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [99]:
X = df_pax_gate_1000.iloc[:,[9,11,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_1000['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_1000 = df_pax_gate_1000.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       0.981
Model:                                   OLS   Adj. R-squared:                  0.925
Method:                        Least Squares   F-statistic:                     17.40
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):              0.174
Time:                               15:20:40   Log-Likelihood:                -11.945
No. Observations:                          5   AIC:                             31.89
Df Residuals:                              1   BIC:                             30.33
Df Model:                                  3
Covariance Type:                   nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
#stores         -134.1297     27.179     -4.935      0.127    -479.470     211.210
#offices          66.6539     34.111      1.954      0.301    -366.773     500.081
#waiting seats    18.0097     21.055      0.855      0.550    -249.523     285.543
const             26.7367     16.279      1.642      0.348    -180.104     233.577
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.850
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.183
Skew:                           0.285   Prob(JB):                        0.913
Kurtosis:                       2.255   Cond. No.                         22.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [100]:
X = df_pax_gate_1000.iloc[:,[8,11,12]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_gate_1000['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_gate_1000 = df_pax_gate_1000.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       0.974
Model:                                  OLS   Adj. R-squared:                  0.896
Method:                       Least Squares   F-statistic:                     12.54
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):              0.204
Time:                              15:20:40   Log-Likelihood:                -5.7948
No. Observations:                         5   AIC:                             19.59
Df Residuals:                             1   BIC:                             18.03
Df Model:                                 3
Covariance Type:                  nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
faculty area     4.7835      6.823      0.701      0.611     -81.917      91.484
#offices       -22.9011      7.695     -2.976      0.206    -120.676      74.874
#dorms        -170.2638     42.468     -4.009      0.156    -709.873     369.346
const           26.3144      3.252      8.092      0.078     -15.004      67.633
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.838
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.766
Skew:                           0.936   Prob(JB):                        0.682
Kurtosis:                       2.583   Cond. No.                         65.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [101]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_gate_900['#waiting passengers (y)'], df_pax_gate_1000['predict_waiting_passengers']))
RMSE_waiting_passengers

36.405479336898225

In [102]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_gate_1000['#departing passengers (y)'], df_pax_gate_1000['predict_departing_passengers']))
RMSE_departing_passengers

2.638193849459028

In [103]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_gate_1000['#arriving passengers (y)'], df_pax_gate_1000['predict_arriving_passengers']))
RMSE_arriving_passengers

0.771061465560251

## Predict inside U

In [104]:
df_pax_inside = df_pax[25:50]
df_pax_inside = df_pax_inside.reset_index(drop = True)
df_pax_inside

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,ศร.1,8:00-8:30,5,7,20,0.864445,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
1,ศร.1,8:30-9:00,1,4,15,0.247519,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
2,ศร.1,9:00-9:30,1,7,14,0.870062,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
3,ศร.1,9:30-10:00,4,5,5,1.000000,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
4,ศร.1,10:00-10:30,0,3,6,0.363228,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
5,หอสมุด,8:00-8:30,2,8,26,0.007676,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
6,หอสมุด,8:30-9:00,0,4,33,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
7,หอสมุด,9:00-9:30,2,0,13,0.003745,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
8,หอสมุด,9:30-10:00,1,10,20,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
9,หอสมุด,10:00-10:30,2,10,6,0.014042,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
10,บาร์ใหม่,8:00-8:30,3,6,2,0.789811,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
11,บาร์ใหม่,8:30-9:00,0,0,3,0.230718,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
12,บาร์ใหม่,9:00-9:30,1,2,4,0.735519,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
13,บาร์ใหม่,9:30-10:00,0,0,5,0.795138,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
14,บาร์ใหม่,10:00-10:30,2,0,0,0.225119,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
15,อาคารจักร,8:00-8:30,0,0,14,0.849092,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
16,อาคารจักร,8:30-9:00,0,0,30,0.200150,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
17,อาคารจักร,9:00-9:30,3,3,24,0.461711,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
18,อาคารจักร,9:30-10:00,3,4,26,0.962741,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
19,อาคารจักร,10:00-10:30,2,1,9,0.419023,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
20,RDIPT,8:00-8:30,4,1,32,0.512451,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
21,RDIPT,8:30-9:00,0,3,19,0.156151,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
22,RDIPT,9:00-9:30,10,13,22,0.250328,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
23,RDIPT,9:30-10:00,0,5,17,0.761281,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
24,RDIPT,10:00-10:30,7,3,17,0.356488,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

## 8:00 - 8:30

In [105]:
df_pax_inside_800 = df_pax_inside[df_pax_inside['time'] == '8:00-8:30'].copy()
df_pax_inside_800

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,ศร.1,8:00-8:30,5,7,20,0.864445,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
5,หอสมุด,8:00-8:30,2,8,26,0.007676,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
10,บาร์ใหม่,8:00-8:30,3,6,2,0.789811,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
15,อาคารจักร,8:00-8:30,0,0,14,0.849092,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
20,RDIPT,8:00-8:30,4,1,32,0.512451,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [106]:
X = df_pax_inside_800.iloc[:,[6,9,10,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_800['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_800 = df_pax_inside_800.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1698: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1699: RuntimeWarning: invalid value encountered in double_scalars
  * (1 - self.rsquared))
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1620: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       1.000
Model:                                 OLS   Adj. R-squared:                    nan
Method:                      Least Squares   F-statistic:                       nan
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                             15:20:40   Log-Likelihood:                 159.82
No. Observations:                        5   AIC:                            -309.6
Df Residuals:                            0   BIC:                            -311.6
Df Model:                                4
Covariance Type:                 nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -32.6850        inf         -0        nan         nan         nan
#stores                     -1.2109        inf         -0        nan         nan         nan
#banks                      12.0117        inf          0        nan         nan         nan
#waiting seats               2.5370        inf          0        nan         nan         nan
const                       28.8861        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.500
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.638
Skew:                           0.000   Prob(JB):                        0.727
Kurtosis:                       1.250   Cond. No.                         108.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [107]:
X = df_pax_inside_800.iloc[:,[6,10,14,15]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_800['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_800 = df_pax_inside_800.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       1.000
Model:                                   OLS   Adj. R-squared:                    nan
Method:                        Least Squares   F-statistic:                       nan
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                               15:20:40   Log-Likelihood:                 158.46
No. Observations:                          5   AIC:                            -306.9
Df Residuals:                              0   BIC:                            -308.9
Df Model:                                  4
Covariance Type:                   nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -10.6063        inf         -0        nan         nan         nan
#banks                      -1.3403        inf         -0        nan         nan         nan
#routes                     13.3807        inf          0        nan         nan         nan
#main entrances              7.7575        inf          0        nan         nan         nan
const                        9.0913        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   3.000
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.271
Skew:                           0.500   Prob(JB):                        0.873
Kurtosis:                       2.453   Cond. No.                         63.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [108]:
X = df_pax_inside_800.iloc[:,[5,9,10,13,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_800['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_800 = df_pax_inside_800.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       1.000
Model:                                  OLS   Adj. R-squared:                    nan
Method:                       Least Squares   F-statistic:                       nan
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                              15:20:40   Log-Likelihood:                 152.09
No. Observations:                         5   AIC:                            -294.2
Df Residuals:                             0   BIC:                            -296.1
Df Model:                                 4
Covariance Type:                  nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from buildings   -11.8413        inf         -0        nan         nan         nan
#stores                    -42.5051        inf         -0        nan         nan         nan
#banks                     -13.1817        inf         -0        nan         nan         nan
#waiting seats             -53.0796        inf         -0        nan         nan         nan
#routes                     87.4121        inf          0        nan         nan         nan
const                       54.5886        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.864
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.690
Skew:                           0.212   Prob(JB):                        0.708
Kurtosis:                       1.230   Cond. No.                         19.9
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [109]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_inside_800['#waiting passengers (y)'], df_pax_inside_800['predict_waiting_passengers']))
RMSE_waiting_passengers

3.1776437161565094e-15

In [110]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_inside_800['#departing passengers (y)'], df_pax_inside_800['predict_departing_passengers']))
RMSE_departing_passengers

4.165926057296536e-15

In [111]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_inside_800['#arriving passengers (y)'], df_pax_inside_800['predict_arriving_passengers']))
RMSE_arriving_passengers

1.4904470165364382e-14

## 8:30 - 9:00

In [112]:
df_pax_inside_830 = df_pax_inside[df_pax_inside['time'] == '8:30-9:00'].copy()
df_pax_inside_830

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
1,ศร.1,8:30-9:00,1,4,15,0.247519,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
6,หอสมุด,8:30-9:00,0,4,33,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
11,บาร์ใหม่,8:30-9:00,0,0,3,0.230718,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
16,อาคารจักร,8:30-9:00,0,0,30,0.200150,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
21,RDIPT,8:30-9:00,0,3,19,0.156151,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [113]:
X = df_pax_inside_830.iloc[:,[6,9,10,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_830['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_830 = df_pax_inside_830.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       1.000
Model:                                 OLS   Adj. R-squared:                    nan
Method:                      Least Squares   F-statistic:                       nan
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                             15:20:41   Log-Likelihood:                 160.76
No. Observations:                        5   AIC:                            -311.5
Df Residuals:                            0   BIC:                            -313.5
Df Model:                                4
Covariance Type:                 nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -11.5199        inf         -0        nan         nan         nan
#stores                      2.2328        inf          0        nan         nan         nan
#banks                       2.4200        inf          0        nan         nan         nan
#waiting seats               0.0583        inf          0        nan         nan         nan
const                        8.2704        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.455
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.747
Skew:                          -0.913   Prob(JB):                        0.688
Kurtosis:                       2.500   Cond. No.                         108.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1698: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1699: RuntimeWarning: invalid value encountered in double_scalars
  * (1 - self.rsquared))
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1620: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

In [114]:
X = df_pax_inside_830.iloc[:,[6,10,14,15]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_830['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_830 = df_pax_inside_830.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       1.000
Model:                                   OLS   Adj. R-squared:                    nan
Method:                        Least Squares   F-statistic:                       nan
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                               15:20:41   Log-Likelihood:                 155.45
No. Observations:                          5   AIC:                            -300.9
Df Residuals:                              0   BIC:                            -302.8
Df Model:                                  4
Covariance Type:                   nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -31.8188        inf         -0        nan         nan         nan
#banks                       7.9791        inf          0        nan         nan         nan
#routes                      7.1421        inf          0        nan         nan         nan
#main entrances             -0.7275        inf         -0        nan         nan         nan
const                       27.2738        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.565
Prob(Omnibus):                    nan   Jarque-Bera (JB):                1.125
Skew:                           1.150   Prob(JB):                        0.570
Kurtosis:                       2.666   Cond. No.                         63.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [115]:
X = df_pax_inside_830.iloc[:,[5,9,10,13,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_830['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_830 = df_pax_inside_830.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       1.000
Model:                                  OLS   Adj. R-squared:                    nan
Method:                       Least Squares   F-statistic:                       nan
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                              15:20:41   Log-Likelihood:                 152.70
No. Observations:                         5   AIC:                            -295.4
Df Residuals:                             0   BIC:                            -297.4
Df Model:                                 4
Covariance Type:                  nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from buildings    -4.1768        inf         -0        nan         nan         nan
#stores                     14.3437        inf          0        nan         nan         nan
#banks                     -44.9597        inf         -0        nan         nan         nan
#waiting seats             -32.4347        inf         -0        nan         nan         nan
#routes                     55.8738        inf          0        nan         nan         nan
const                       20.5319        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.014
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.378
Skew:                          -0.594   Prob(JB):                        0.828
Kurtosis:                       2.362   Cond. No.                         18.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [116]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_inside_830['#waiting passengers (y)'], df_pax_inside_830['predict_waiting_passengers']))
RMSE_waiting_passengers

2.6347629809804343e-15

In [117]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_inside_830['#departing passengers (y)'], df_pax_inside_830['predict_departing_passengers']))
RMSE_departing_passengers

7.619721951899982e-15

In [118]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_inside_830['#arriving passengers (y)'], df_pax_inside_830['predict_arriving_passengers']))
RMSE_arriving_passengers

1.3197745560238665e-14

## 9:00 - 9:30

In [119]:
df_pax_inside_900 = df_pax_inside[df_pax_inside['time'] == '9:00-9:30'].copy()
df_pax_inside_900

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
2,ศร.1,9:00-9:30,1,7,14,0.870062,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
7,หอสมุด,9:00-9:30,2,0,13,0.003745,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
12,บาร์ใหม่,9:00-9:30,1,2,4,0.735519,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
17,อาคารจักร,9:00-9:30,3,3,24,0.461711,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
22,RDIPT,9:00-9:30,10,13,22,0.250328,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [120]:
X = df_pax_inside_900.iloc[:,[6,9,10,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_900['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_900 = df_pax_inside_900.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       1.000
Model:                                 OLS   Adj. R-squared:                    nan
Method:                      Least Squares   F-statistic:                       nan
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                             15:20:41   Log-Likelihood:                 156.35
No. Observations:                        5   AIC:                            -302.7
Df Residuals:                            0   BIC:                            -304.7
Df Model:                                4
Covariance Type:                 nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -69.0328        inf         -0        nan         nan         nan
#stores                     -0.4284        inf         -0        nan         nan         nan
#banks                       9.5775        inf          0        nan         nan         nan
#waiting seats               2.1956        inf          0        nan         nan         nan
const                       62.4800        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.500
Prob(Omnibus):                    nan   Jarque-Bera (JB):                1.888
Skew:                          -1.500   Prob(JB):                        0.389
Kurtosis:                       3.250   Cond. No.                         108.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1698: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1699: RuntimeWarning: invalid value encountered in double_scalars
  * (1 - self.rsquared))
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1620: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

In [121]:
X = df_pax_inside_900.iloc[:,[6,10,14,15]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_900['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_900 = df_pax_inside_900.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       1.000
Model:                                   OLS   Adj. R-squared:                    nan
Method:                        Least Squares   F-statistic:                       nan
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                               15:20:41   Log-Likelihood:                 149.42
No. Observations:                          5   AIC:                            -288.8
Df Residuals:                              0   BIC:                            -290.8
Df Model:                                  4
Covariance Type:                   nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties  -106.0626        inf         -0        nan         nan         nan
#banks                      25.3971        inf          0        nan         nan         nan
#routes                     -0.3930        inf         -0        nan         nan         nan
#main entrances             -2.8250        inf         -0        nan         nan         nan
const                       93.9126        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.562
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.770
Skew:                           0.844   Prob(JB):                        0.680
Kurtosis:                       2.078   Cond. No.                         63.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [122]:
X = df_pax_inside_900.iloc[:,[5,9,10,13,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_900['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_900 = df_pax_inside_900.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       1.000
Model:                                  OLS   Adj. R-squared:                    nan
Method:                       Least Squares   F-statistic:                       nan
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                              15:20:41   Log-Likelihood:                 152.81
No. Observations:                         5   AIC:                            -295.6
Df Residuals:                             0   BIC:                            -297.6
Df Model:                                 4
Covariance Type:                  nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from buildings   -18.7462        inf         -0        nan         nan         nan
#stores                      0.1625        inf          0        nan         nan         nan
#banks                     -17.9628        inf         -0        nan         nan         nan
#waiting seats             -45.8880        inf         -0        nan         nan         nan
#routes                     37.7349        inf          0        nan         nan         nan
const                       32.5386        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.288
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.663
Skew:                          -0.700   Prob(JB):                        0.718
Kurtosis:                       1.895   Cond. No.                         18.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

In [123]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_inside_900['#waiting passengers (y)'], df_pax_inside_900['predict_waiting_passengers']))
RMSE_waiting_passengers

6.355287432313019e-15

In [124]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_inside_900['#departing passengers (y)'], df_pax_inside_900['predict_departing_passengers']))
RMSE_departing_passengers

2.5421149729252075e-14

In [125]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_inside_900['#arriving passengers (y)'], df_pax_inside_900['predict_arriving_passengers']))
RMSE_arriving_passengers

1.2907649793152806e-14

## 9:30 - 10:00

In [126]:
df_pax_inside_930 = df_pax_inside[df_pax_inside['time'] == '9:30-10:00'].copy()
df_pax_inside_930

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
3,ศร.1,9:30-10:00,4,5,5,1.000000,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
8,หอสมุด,9:30-10:00,1,10,20,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
13,บาร์ใหม่,9:30-10:00,0,0,5,0.795138,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
18,อาคารจักร,9:30-10:00,3,4,26,0.962741,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
23,RDIPT,9:30-10:00,0,5,17,0.761281,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [127]:
X = df_pax_inside_930.iloc[:,[6,9,10,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_930['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_930 = df_pax_inside_930.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1698: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       1.000
Model:                                 OLS   Adj. R-squared:                    nan
Method:                      Least Squares   F-statistic:                       nan
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                             15:20:41   Log-Likelihood:                 156.35
No. Observations:                        5   AIC:                            -302.7
Df Residuals:                            0   BIC:                            -304.7
Df Model:                                4
Covariance Type:                 nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -44.1827        inf         -0        nan         nan         nan
#stores                     14.1506        inf          0        nan         nan         nan
#banks                       3.9909        inf          0        nan         nan         nan
#waiting seats              -1.8317        inf         -0        nan         nan         nan
const                       30.7063        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.875
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.305
Skew:                          -0.054   Prob(JB):                        0.859
Kurtosis:                       1.796   Cond. No.                         108.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1699: RuntimeWarning: invalid value encountered in double_scalars
  * (1 - self.rsquared))
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1620: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

In [128]:
X = df_pax_inside_930.iloc[:,[6,10,14,15]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_930['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_930 = df_pax_inside_930.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       1.000
Model:                                   OLS   Adj. R-squared:                    nan
Method:                        Least Squares   F-statistic:                       nan
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                               15:20:41   Log-Likelihood:                 161.26
No. Observations:                          5   AIC:                            -312.5
Df Residuals:                              0   BIC:                            -314.5
Df Model:                                  4
Covariance Type:                   nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -10.6063        inf         -0        nan         nan         nan
#banks                       2.6597        inf          0        nan         nan         nan
#routes                      9.3807        inf          0        nan         nan         nan
#main entrances             -4.2425        inf         -0        nan         nan         nan
const                       13.0913        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.111
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.242
Skew:                           0.370   Prob(JB):                        0.886
Kurtosis:                       2.217   Cond. No.                         63.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [129]:
X = df_pax_inside_930.iloc[:,[5,9,10,13,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_930['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_930 = df_pax_inside_930.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       1.000
Model:                                  OLS   Adj. R-squared:                    nan
Method:                       Least Squares   F-statistic:                       nan
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                              15:20:41   Log-Likelihood:                 157.39
No. Observations:                         5   AIC:                            -304.8
Df Residuals:                             0   BIC:                            -306.7
Df Model:                                 4
Covariance Type:                  nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from buildings    11.7892        inf          0        nan         nan         nan
#stores                     12.9924        inf          0        nan         nan         nan
#banks                     -37.1013        inf         -0        nan         nan         nan
#waiting seats              -2.0383        inf         -0        nan         nan         nan
#routes                     17.4583        inf          0        nan         nan         nan
const                        5.3168        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.473
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.663
Skew:                          -0.170   Prob(JB):                        0.718
Kurtosis:                       1.248   Cond. No.                         18.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

In [130]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_inside_930['#waiting passengers (y)'], df_pax_inside_930['predict_waiting_passengers']))
RMSE_waiting_passengers

6.355287432313019e-15

In [131]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_inside_930['#departing passengers (y)'], df_pax_inside_930['predict_departing_passengers']))
RMSE_departing_passengers

2.383232787117382e-15

In [132]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_inside_930['#arriving passengers (y)'], df_pax_inside_930['predict_arriving_passengers']))
RMSE_arriving_passengers

5.1636710387543275e-15

## 10:00 - 10:30

In [133]:
df_pax_inside_1000 = df_pax_inside[df_pax_inside['time'] == '10:00-10:30'].copy()
df_pax_inside_1000

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
4,ศร.1,10:00-10:30,0,3,6,0.363228,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
9,หอสมุด,10:00-10:30,2,10,6,0.014042,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
14,บาร์ใหม่,10:00-10:30,2,0,0,0.225119,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
19,อาคารจักร,10:00-10:30,2,1,9,0.419023,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
24,RDIPT,10:00-10:30,7,3,17,0.356488,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [134]:
X = df_pax_inside_1000.iloc[:,[6,9,10,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_1000['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_1000 = df_pax_inside_1000.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1698: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       1.000
Model:                                 OLS   Adj. R-squared:                    nan
Method:                      Least Squares   F-statistic:                       nan
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                             15:20:41   Log-Likelihood:                 157.07
No. Observations:                        5   AIC:                            -304.1
Df Residuals:                            0   BIC:                            -306.1
Df Model:                                4
Covariance Type:                 nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -15.7009        inf         -0        nan         nan         nan
#stores                     -6.7510        inf         -0        nan         nan         nan
#banks                       2.5728        inf          0        nan         nan         nan
#waiting seats               1.6616        inf          0        nan         nan         nan
const                       20.3079        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.083
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.642
Skew:                          -0.868   Prob(JB):                        0.725
Kurtosis:                       2.729   Cond. No.                         108.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1699: RuntimeWarning: invalid value encountered in double_scalars
  * (1 - self.rsquared))
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1620: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

In [135]:
X = df_pax_inside_1000.iloc[:,[6,10,14,15]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_1000['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_1000 = df_pax_inside_1000.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       1.000
Model:                                   OLS   Adj. R-squared:                    nan
Method:                        Least Squares   F-statistic:                       nan
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                               15:20:41   Log-Likelihood:                 157.29
No. Observations:                          5   AIC:                            -304.6
Df Residuals:                              0   BIC:                            -306.5
Df Model:                                  4
Covariance Type:                   nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -21.2125        inf         -0        nan         nan         nan
#banks                      -2.2806        inf         -0        nan         nan         nan
#routes                     16.1614        inf          0        nan         nan         nan
#main entrances              2.3150        inf          0        nan         nan         nan
const                       19.1825        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.818
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.747
Skew:                           0.913   Prob(JB):                        0.688
Kurtosis:                       2.500   Cond. No.                         63.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [136]:
X = df_pax_inside_1000.iloc[:,[5,9,10,13,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_inside_1000['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_inside_1000 = df_pax_inside_1000.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       1.000
Model:                                  OLS   Adj. R-squared:                    nan
Method:                       Least Squares   F-statistic:                       nan
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                              15:20:41   Log-Likelihood:                 150.80
No. Observations:                         5   AIC:                            -291.6
Df Residuals:                             0   BIC:                            -293.5
Df Model:                                 4
Covariance Type:                  nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from buildings    26.6955        inf          0        nan         nan         nan
#stores                    -21.9940        inf         -0        nan         nan         nan
#banks                      -6.1591        inf         -0        nan         nan         nan
#waiting seats              -8.6047        inf         -0        nan         nan         nan
#routes                     29.4489        inf          0        nan         nan         nan
const                       13.6138        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.092
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.646
Skew:                           0.254   Prob(JB):                        0.724
Kurtosis:                       1.314   Cond. No.                         15.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

In [137]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_inside_1000['#waiting passengers (y)'], df_pax_inside_1000['predict_waiting_passengers']))
RMSE_waiting_passengers

5.503840364735051e-15

In [138]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_inside_1000['#departing passengers (y)'], df_pax_inside_1000['predict_departing_passengers']))
RMSE_departing_passengers

5.2695259619608686e-15

In [139]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_inside_1000['#arriving passengers (y)'], df_pax_inside_1000['predict_arriving_passengers']))
RMSE_arriving_passengers

1.930434903399765e-14

## Predict by using the education building.

In [140]:
df_pax_edu = df_pax[(df_pax['location'] == 'ศร.1') | (df_pax['location'] == 'หอสมุด') | (df_pax['location'] == 'อาคารจักร') | (df_pax['location'] == 'RDIPT')]
df_pax_edu

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
25,ศร.1,8:00-8:30,5,7,20,0.864445,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
26,ศร.1,8:30-9:00,1,4,15,0.247519,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
27,ศร.1,9:00-9:30,1,7,14,0.870062,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
28,ศร.1,9:30-10:00,4,5,5,1.000000,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
29,ศร.1,10:00-10:30,0,3,6,0.363228,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
30,หอสมุด,8:00-8:30,2,8,26,0.007676,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
31,หอสมุด,8:30-9:00,0,4,33,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
32,หอสมุด,9:00-9:30,2,0,13,0.003745,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
33,หอสมุด,9:30-10:00,1,10,20,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
34,หอสมุด,10:00-10:30,2,10,6,0.014042,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
40,อาคารจักร,8:00-8:30,0,0,14,0.849092,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
41,อาคารจักร,8:30-9:00,0,0,30,0.200150,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
42,อาคารจักร,9:00-9:30,3,3,24,0.461711,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
43,อาคารจักร,9:30-10:00,3,4,26,0.962741,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
44,อาคารจักร,10:00-10:30,2,1,9,0.419023,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
45,RDIPT,8:00-8:30,4,1,32,0.512451,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
46,RDIPT,8:30-9:00,0,3,19,0.156151,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
47,RDIPT,9:00-9:30,10,13,22,0.250328,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
48,RDIPT,9:30-10:00,0,5,17,0.761281,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
49,RDIPT,10:00-10:30,7,3,17,0.356488,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

## 8:00 - 8:30

In [141]:
df_pax_edu_800 = df_pax_edu[df_pax_edu['time'] == '8:00-8:30'].copy()
df_pax_edu_800

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
25,ศร.1,8:00-8:30,5,7,20,0.864445,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
30,หอสมุด,8:00-8:30,2,8,26,0.007676,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
40,อาคารจักร,8:00-8:30,0,0,14,0.849092,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
45,RDIPT,8:00-8:30,4,1,32,0.512451,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [142]:
X = df_pax_edu_800.iloc[:,[5,6,10,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_800['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_800 = df_pax_edu_800.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       1.000
Model:                                 OLS   Adj. R-squared:                    nan
Method:                      Least Squares   F-statistic:                       nan
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                             15:20:41   Log-Likelihood:                 127.17
No. Observations:                        4   AIC:                            -246.3
Df Residuals:                            0   BIC:                            -248.8
Df Model:                                3
Covariance Type:                 nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from buildings   -15.7722        inf         -0        nan         nan         nan
#students from faculties    -4.2762        inf         -0        nan         nan         nan
#banks                       7.0235        inf          0        nan         nan         nan
#waiting seats             -13.3595        inf         -0        nan         nan         nan
const                       17.0574        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.500
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.805
Skew:                          -1.027   Prob(JB):                        0.669
Kurtosis:                       2.218   Cond. No.                         27.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1698: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1699: RuntimeWarning: invalid value encountered in double_scalars
  * (1 - self.rsquared))
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1620: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

In [143]:
X = df_pax_edu_800.iloc[:,[6,10,13,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_800['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_800 = df_pax_edu_800.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       1.000
Model:                                   OLS   Adj. R-squared:                    nan
Method:                        Least Squares   F-statistic:                       nan
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                               15:20:41   Log-Likelihood:                 130.06
No. Observations:                          4   AIC:                            -252.1
Df Residuals:                              0   BIC:                            -254.6
Df Model:                                  3
Covariance Type:                   nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties    -2.4878        inf         -0        nan         nan         nan
#banks                       7.9879        inf          0        nan         nan         nan
#waiting seats               5.9705        inf          0        nan         nan         nan
#routes                      2.0963        inf          0        nan         nan         nan
const                        2.1324        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.824
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.419
Skew:                           0.652   Prob(JB):                        0.811
Kurtosis:                       2.097   Cond. No.                         39.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

In [144]:
X = df_pax_edu_800.iloc[:,[6,9,11,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_800['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_800 = df_pax_edu_800.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       1.000
Model:                                  OLS   Adj. R-squared:                    nan
Method:                       Least Squares   F-statistic:                       nan
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                              15:20:41   Log-Likelihood:                 118.71
No. Observations:                         4   AIC:                            -229.4
Df Residuals:                             0   BIC:                            -231.9
Df Model:                                 3
Covariance Type:                  nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties    31.8436        inf          0        nan         nan         nan
#stores                    -57.9412        inf         -0        nan         nan         nan
#offices                    17.6229        inf          0        nan         nan         nan
#routes                     52.6940        inf          0        nan         nan         nan
const                       10.9100        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.158
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.421
Skew:                          -0.499   Prob(JB):                        0.810
Kurtosis:                       1.762   Cond. No.                         38.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)

In [145]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_edu_800['#waiting passengers (y)'], df_pax_edu_800['predict_waiting_passengers']))
RMSE_waiting_passengers

3.76822190084106e-15

In [146]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_edu_800['#departing passengers (y)'], df_pax_edu_800['predict_departing_passengers']))
RMSE_departing_passengers

1.831026719408895e-15

In [147]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_edu_800['#arriving passengers (y)'], df_pax_edu_800['predict_arriving_passengers']))
RMSE_arriving_passengers

3.1275989552275635e-14

## 8:30 - 9:00

In [148]:
df_pax_edu_830 = df_pax_edu[df_pax_edu['time'] == '8:30-9:00'].copy()
df_pax_edu_830

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
26,ศร.1,8:30-9:00,1,4,15,0.247519,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
31,หอสมุด,8:30-9:00,0,4,33,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
41,อาคารจักร,8:30-9:00,0,0,30,0.200150,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
46,RDIPT,8:30-9:00,0,3,19,0.156151,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [149]:
X = df_pax_edu_830.iloc[:,[5,6,10,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_830['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_830 = df_pax_edu_830.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       1.000
Model:                                 OLS   Adj. R-squared:                    nan
Method:                      Least Squares   F-statistic:                       nan
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                             15:20:41   Log-Likelihood:                 136.19
No. Observations:                        4   AIC:                            -264.4
Df Residuals:                            0   BIC:                            -266.8
Df Model:                                3
Covariance Type:                 nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from buildings     0.0611        inf          0        nan         nan         nan
#students from faculties    -0.2919        inf         -0        nan         nan         nan
#banks                       1.2466        inf          0        nan         nan         nan
#waiting seats              -0.1937        inf         -0        nan         nan         nan
const                        0.2380        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.455
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.809
Skew:                          -1.036   Prob(JB):                        0.667
Kurtosis:                       2.252   Cond. No.                         49.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1698: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1699: RuntimeWarning: invalid value encountered in double_scalars
  * (1 - self.rsquared))
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1620: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

In [150]:
X = df_pax_edu_830.iloc[:,[6,10,13,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_830['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_830 = df_pax_edu_830.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       1.000
Model:                                   OLS   Adj. R-squared:                    nan
Method:                        Least Squares   F-statistic:                       nan
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                               15:20:41   Log-Likelihood:                 131.57
No. Observations:                          4   AIC:                            -255.1
Df Residuals:                              0   BIC:                            -257.6
Df Model:                                  3
Covariance Type:                   nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -15.4012        inf         -0        nan         nan         nan
#banks                      12.2518        inf          0        nan         nan         nan
#waiting seats              12.0737        inf          0        nan         nan         nan
#routes                    -12.0298        inf         -0        nan         nan         nan
const                       13.2013        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.500
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.167
Skew:                           0.000   Prob(JB):                        0.920
Kurtosis:                       2.000   Cond. No.                         39.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

In [151]:
X = df_pax_edu_830.iloc[:,[6,9,11,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_830['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_830 = df_pax_edu_830.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       1.000
Model:                                  OLS   Adj. R-squared:                    nan
Method:                       Least Squares   F-statistic:                       nan
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                              15:20:42   Log-Likelihood:                 127.41
No. Observations:                         4   AIC:                            -246.8
Df Residuals:                             0   BIC:                            -249.3
Df Model:                                 3
Covariance Type:                  nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -20.7280        inf         -0        nan         nan         nan
#stores                     79.1245        inf          0        nan         nan         nan
#offices                   -61.6346        inf         -0        nan         nan         nan
#routes                   -100.8197        inf         -0        nan         nan         nan
const                       51.8447        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.000
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.963
Skew:                           1.155   Prob(JB):                        0.618
Kurtosis:                       2.333   Cond. No.                         38.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)

In [152]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_edu_830['#waiting passengers (y)'], df_pax_edu_830['predict_waiting_passengers']))
RMSE_waiting_passengers

3.9594279570806816e-16

In [153]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_edu_830['#departing passengers (y)'], df_pax_edu_830['predict_departing_passengers']))
RMSE_departing_passengers

1.2560739669470201e-15

In [154]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_edu_830['#arriving passengers (y)'], df_pax_edu_830['predict_arriving_passengers']))
RMSE_arriving_passengers

3.552713678800501e-15

## 9:00 - 9:30

In [155]:
df_pax_edu_900 = df_pax_edu[df_pax_edu['time'] == '9:00-9:30'].copy()
df_pax_edu_900

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
27,ศร.1,9:00-9:30,1,7,14,0.870062,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
32,หอสมุด,9:00-9:30,2,0,13,0.003745,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
42,อาคารจักร,9:00-9:30,3,3,24,0.461711,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
47,RDIPT,9:00-9:30,10,13,22,0.250328,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [156]:
X = df_pax_edu_900.iloc[:,[5,6,10,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_900['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_900 = df_pax_edu_900.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       1.000
Model:                                 OLS   Adj. R-squared:                    nan
Method:                      Least Squares   F-statistic:                       nan
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                             15:20:42   Log-Likelihood:                 124.19
No. Observations:                        4   AIC:                            -240.4
Df Residuals:                            0   BIC:                            -242.8
Df Model:                                3
Covariance Type:                 nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from buildings   -36.7525        inf         -0        nan         nan         nan
#students from faculties   -21.1924        inf         -0        nan         nan         nan
#banks                      19.2420        inf          0        nan         nan         nan
#waiting seats             -21.5825        inf         -0        nan         nan         nan
const                       38.1343        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.600
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.419
Skew:                           0.652   Prob(JB):                        0.811
Kurtosis:                       2.097   Cond. No.                         34.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1698: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1699: RuntimeWarning: invalid value encountered in double_scalars
  * (1 - self.rsquared))
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1620: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

In [157]:
X = df_pax_edu_900.iloc[:,[6,10,13,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_900['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_900 = df_pax_edu_900.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       1.000
Model:                                   OLS   Adj. R-squared:                    nan
Method:                        Least Squares   F-statistic:                       nan
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                               15:20:42   Log-Likelihood:                 125.21
No. Observations:                          4   AIC:                            -242.4
Df Residuals:                              0   BIC:                            -244.9
Df Model:                                  3
Covariance Type:                   nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -58.0953        inf         -0        nan         nan         nan
#banks                      37.2590        inf          0        nan         nan         nan
#waiting seats              35.2759        inf          0        nan         nan         nan
#routes                    -56.2525        inf         -0        nan         nan         nan
const                       52.7970        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.667
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.476
Skew:                          -0.493   Prob(JB):                        0.788
Kurtosis:                       1.628   Cond. No.                         39.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

In [158]:
X = df_pax_edu_900.iloc[:,[6,9,11,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_900['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_900 = df_pax_edu_900.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       1.000
Model:                                  OLS   Adj. R-squared:                    nan
Method:                       Least Squares   F-statistic:                       nan
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                              15:20:42   Log-Likelihood:                 119.73
No. Observations:                         4   AIC:                            -231.5
Df Residuals:                             0   BIC:                            -233.9
Df Model:                                 3
Covariance Type:                  nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties    -2.7187        inf         -0        nan         nan         nan
#stores                     18.3483        inf          0        nan         nan         nan
#offices                   -16.0786        inf         -0        nan         nan         nan
#routes                    -43.7765        inf         -0        nan         nan         nan
const                       29.0412        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.060
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.419
Skew:                          -0.652   Prob(JB):                        0.811
Kurtosis:                       2.097   Cond. No.                         38.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)

In [159]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_edu_900['#waiting passengers (y)'], df_pax_edu_900['predict_waiting_passengers']))
RMSE_waiting_passengers

7.944109290391274e-15

In [160]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_edu_900['#departing passengers (y)'], df_pax_edu_900['predict_departing_passengers']))
RMSE_departing_passengers

6.153480596427404e-15

In [161]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_edu_900['#arriving passengers (y)'], df_pax_edu_900['predict_arriving_passengers']))
RMSE_arriving_passengers

2.4242552967656972e-14

## 9:30 - 10:00

In [162]:
df_pax_edu_930 = df_pax_edu[df_pax_edu['time'] == '9:30-10:00'].copy()
df_pax_edu_930

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
28,ศร.1,9:30-10:00,4,5,5,1.000000,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
33,หอสมุด,9:30-10:00,1,10,20,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
43,อาคารจักร,9:30-10:00,3,4,26,0.962741,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
48,RDIPT,9:30-10:00,0,5,17,0.761281,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [163]:
X = df_pax_edu_930.iloc[:,[5,6,10,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_930['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_930 = df_pax_edu_930.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       1.000
Model:                                 OLS   Adj. R-squared:                    nan
Method:                      Least Squares   F-statistic:                       nan
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                             15:20:42   Log-Likelihood:                 127.98
No. Observations:                        4   AIC:                            -248.0
Df Residuals:                            0   BIC:                            -250.4
Df Model:                                3
Covariance Type:                 nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from buildings     4.8541        inf          0        nan         nan         nan
#students from faculties    23.8705        inf          0        nan         nan         nan
#banks                      -3.1086        inf         -0        nan         nan         nan
#waiting seats               1.7825        inf          0        nan         nan         nan
const                      -22.1341        inf         -0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.333
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.963
Skew:                          -1.155   Prob(JB):                        0.618
Kurtosis:                       2.333   Cond. No.                         53.9
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1698: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1699: RuntimeWarning: invalid value encountered in double_scalars
  * (1 - self.rsquared))
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1620: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

In [164]:
X = df_pax_edu_930.iloc[:,[6,10,13,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_930['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_930 = df_pax_edu_930.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       1.000
Model:                                   OLS   Adj. R-squared:                    nan
Method:                        Least Squares   F-statistic:                       nan
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                               15:20:42   Log-Likelihood:                 126.68
No. Observations:                          4   AIC:                            -245.4
Df Residuals:                              0   BIC:                            -247.8
Df Model:                                  3
Covariance Type:                   nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties    -1.4601        inf         -0        nan         nan         nan
#banks                       1.6292        inf          0        nan         nan         nan
#waiting seats               6.7262        inf          0        nan         nan         nan
#routes                     -0.4473        inf         -0        nan         nan         nan
const                        5.2515        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.087
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.476
Skew:                           0.493   Prob(JB):                        0.788
Kurtosis:                       1.628   Cond. No.                         39.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

In [165]:
X = df_pax_edu_930.iloc[:,[6,9,11,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_930['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_930 = df_pax_edu_930.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       1.000
Model:                                  OLS   Adj. R-squared:                    nan
Method:                       Least Squares   F-statistic:                       nan
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                              15:20:42   Log-Likelihood:                 124.09
No. Observations:                         4   AIC:                            -240.2
Df Residuals:                             0   BIC:                            -242.6
Df Model:                                 3
Covariance Type:                  nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties   -25.1637        inf         -0        nan         nan         nan
#stores                     76.7429        inf          0        nan         nan         nan
#offices                   -62.6267        inf         -0        nan         nan         nan
#routes                   -114.8722        inf         -0        nan         nan         nan
const                       54.3382        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.095
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.963
Skew:                          -1.155   Prob(JB):                        0.618
Kurtosis:                       2.333   Cond. No.                         38.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

In [166]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_edu_930['#waiting passengers (y)'], df_pax_edu_930['predict_waiting_passengers']))
RMSE_waiting_passengers

3.076740298213702e-15

In [167]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_edu_930['#departing passengers (y)'], df_pax_edu_930['predict_departing_passengers']))
RMSE_departing_passengers

4.259554063523935e-15

In [168]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_edu_930['#arriving passengers (y)'], df_pax_edu_930['predict_arriving_passengers']))
RMSE_arriving_passengers

8.140289677804162e-15

## 10:00 - 10:30

In [169]:
df_pax_edu_1000 = df_pax_edu[df_pax_edu['time'] == '10:00-10:30'].copy()
df_pax_edu_1000

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
29,ศร.1,10:00-10:30,0,3,6,0.363228,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
34,หอสมุด,10:00-10:30,2,10,6,0.014042,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
44,อาคารจักร,10:00-10:30,2,1,9,0.419023,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
49,RDIPT,10:00-10:30,7,3,17,0.356488,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

In [170]:
X = df_pax_edu_1000.iloc[:,[5,6,10,13]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_1000['#waiting passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_1000 = df_pax_edu_1000.assign(predict_waiting_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1698: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1699: RuntimeWarning: invalid value encountered in double_scalars
  * (1 - self.rsquared))
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Users\Nu\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1620: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

                               OLS Regression Results
===================================================================================
Dep. Variable:     #waiting passengers (y)   R-squared:                       1.000
Model:                                 OLS   Adj. R-squared:                    nan
Method:                      Least Squares   F-statistic:                       nan
Date:                     Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                             15:20:42   Log-Likelihood:                 120.42
No. Observations:                        4   AIC:                            -232.8
Df Residuals:                            0   BIC:                            -235.3
Df Model:                                3
Covariance Type:                 nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from buildings     8.1852        inf          0        nan         nan         nan
#students from faculties   -50.2577        inf         -0        nan         nan         nan
#banks                       6.7626        inf          0        nan         nan         nan
#waiting seats               6.0322        inf          0        nan         nan         nan
const                       41.6492        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.273
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.476
Skew:                          -0.493   Prob(JB):                        0.788
Kurtosis:                       1.628   Cond. No.                         49.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

In [171]:
X = df_pax_edu_1000.iloc[:,[6,10,13,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_1000['#departing passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_1000 = df_pax_edu_1000.assign(predict_departing_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)

                                OLS Regression Results
=====================================================================================
Dep. Variable:     #departing passengers (y)   R-squared:                       1.000
Model:                                   OLS   Adj. R-squared:                    nan
Method:                        Least Squares   F-statistic:                       nan
Date:                       Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                               15:20:42   Log-Likelihood:                 129.17
No. Observations:                          4   AIC:                            -250.3
Df Residuals:                              0   BIC:                            -252.8
Df Model:                                  3
Covariance Type:                   nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties    -6.2482        inf         -0        nan         nan         nan
#banks                       4.2611        inf          0        nan         nan         nan
#waiting seats              11.0050        inf          0        nan         nan         nan
#routes                     -1.9753        inf         -0        nan         nan         nan
const                        6.3557        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.472
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.296
Skew:                           0.441   Prob(JB):                        0.862
Kurtosis:                       2.000   Cond. No.                         39.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

In [172]:
X = df_pax_edu_1000.iloc[:,[6,9,11,14]]
X = sm.add_constant(X, prepend=False)
Y = df_pax_edu_1000['#arriving passengers (y)']
model = sm.OLS(Y, X)
results = model.fit()
df_pax_edu_1000 = df_pax_edu_1000.assign(predict_arriving_passengers = results.predict(X))
print(results.summary())

C:\Users\Nu\Anaconda3\lib\site-packages\statsmodels\stats\stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)

                               OLS Regression Results
====================================================================================
Dep. Variable:     #arriving passengers (y)   R-squared:                       1.000
Model:                                  OLS   Adj. R-squared:                    nan
Method:                       Least Squares   F-statistic:                       nan
Date:                      Tue, 31 Mar 2020   Prob (F-statistic):                nan
Time:                              15:20:42   Log-Likelihood:                 121.91
No. Observations:                         4   AIC:                            -235.8
Df Residuals:                             0   BIC:                            -238.3
Df Model:                                 3
Covariance Type:                  nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
#students from faculties    10.2202        inf          0        nan         nan         nan
#stores                    -21.7375        inf         -0        nan         nan         nan
#offices                     4.0213        inf          0        nan         nan         nan
#routes                      4.8462        inf          0        nan         nan         nan
const                       11.8806        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.185
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.595
Skew:                          -0.846   Prob(JB):                        0.743
Kurtosis:                       2.158   Cond. No.                         38.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.

In [173]:
RMSE_waiting_passengers = sqrt(mean_squared_error(df_pax_edu_1000['#waiting passengers (y)'], df_pax_edu_1000['predict_waiting_passengers']))
RMSE_waiting_passengers

2.040878629308206e-14

In [174]:
RMSE_departing_passengers = sqrt(mean_squared_error(df_pax_edu_1000['#departing passengers (y)'], df_pax_edu_1000['predict_departing_passengers']))
RMSE_departing_passengers

2.286089127109703e-15

In [175]:
RMSE_arriving_passengers = sqrt(mean_squared_error(df_pax_edu_1000['#arriving passengers (y)'], df_pax_edu_1000['predict_arriving_passengers']))
RMSE_arriving_passengers

1.4057370193527075e-14

# 2.1.iv Predict stop#1

### use model from inside U

In [176]:
df_pax_1 = df_pax[df_pax['location'] == 'อาคารจักร']
df_pax_1 = df_pax_1.reset_index(drop=True)
df_pax_1

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,อาคารจักร,8:00-8:30,0,0,14,0.849092,0.85716,1.0,1.0,0.718367,0.0,0.988372,0.094595,0.0,0.0,0.0
1,อาคารจักร,8:30-9:00,0,0,30,0.200150,0.85716,1.0,1.0,0.718367,0.0,0.988372,0.094595,0.0,0.0,0.0
2,อาคารจักร,9:00-9:30,3,3,24,0.461711,0.85716,1.0,1.0,0.718367,0.0,0.988372,0.094595,0.0,0.0,0.0
3,อาคารจักร,9:30-10:00,3,4,26,0.962741,0.85716,1.0,1.0,0.718367,0.0,0.988372,0.094595,0.0,0.0,0.0
4,อาคารจักร,10:00-10:30,2,1,9,0.419023,0.85716,1.0,1.0,0.718367,0.0,0.988372,0.094595,0.0,0.0,0.0

In [177]:
df_pax_1.loc[0,'predict_waiting_passengers'] = round(28.8861 + df_pax_1.iloc[0,6]*-32.6850 + df_pax_1.iloc[0,9]*-1.2109 + df_pax_1.iloc[0,10]*12.0117 + df_pax_1.iloc[0,13]*2.5370)
df_pax_1.loc[1,'predict_waiting_passengers'] = round(8.2704 + df_pax_1.iloc[1,6]*-11.5199 + df_pax_1.iloc[0,9]*2.2328 + df_pax_1.iloc[0,10]*2.4200 + df_pax_1.iloc[0,13]*0.0583)
df_pax_1.loc[2,'predict_waiting_passengers'] = round(62.4800 + df_pax_1.iloc[2,6]*-69.0328 + df_pax_1.iloc[0,9]*-0.4284 + df_pax_1.iloc[0,10]*9.5775 + df_pax_1.iloc[0,13]*2.1956)
df_pax_1.loc[3,'predict_waiting_passengers'] = round(30.7063 + df_pax_1.iloc[3,6]*-44.1827 + df_pax_1.iloc[0,9]*14.1506 + df_pax_1.iloc[0,10]*3.9909 + df_pax_1.iloc[0,13]*-1.8317)
df_pax_1.loc[4,'predict_waiting_passengers'] = round(20.3079 + df_pax_1.iloc[4,6]*-15.7009 + df_pax_1.iloc[0,9]*-6.7510 + df_pax_1.iloc[0,10]*2.5728 + df_pax_1.iloc[0,13]*1.6616)

In [178]:
df_pax_1.loc[0,'predict_departing_passengers'] = round(9.0913 + df_pax_1.iloc[0,6]*-10.6063 + df_pax_1.iloc[0,10]*-1.3403 + df_pax_1.iloc[0,14]*13.3807 + df_pax_1.iloc[0,15]*7.7575)
df_pax_1.loc[1,'predict_departing_passengers'] = round(27.2738 + df_pax_1.iloc[1,6]*-31.8188 + df_pax_1.iloc[1,10]*7.9791 + df_pax_1.iloc[1,14]*7.1421 + df_pax_1.iloc[1,15]*-0.7275)
df_pax_1.loc[2,'predict_departing_passengers'] = round(93.9126 + df_pax_1.iloc[2,6]*-106.0626 + df_pax_1.iloc[2,10]*25.3971 + df_pax_1.iloc[2,14]*-0.3930 + df_pax_1.iloc[2,15]*-2.8250)
df_pax_1.loc[3,'predict_departing_passengers'] = round(13.0913 + df_pax_1.iloc[3,6]*-10.6063 + df_pax_1.iloc[3,10]*2.6597 + df_pax_1.iloc[3,14]*9.3807 + df_pax_1.iloc[3,15]*-4.2425)
df_pax_1.loc[4,'predict_departing_passengers'] = round(19.1825 + df_pax_1.iloc[4,6]*-21.2125 + df_pax_1.iloc[4,10]*-2.2806 + df_pax_1.iloc[4,14]*16.1614 + df_pax_1.iloc[4,15]*2.3150)

In [179]:
df_pax_1.loc[0,'predict_arriving_passengers'] = round(54.5886 + df_pax_1.iloc[0,5]*-11.8413 + df_pax_1.iloc[0,9]*-42.5051 + df_pax_1.iloc[0,10]*-13.1817 + df_pax_1.iloc[0,13]*-53.0796 + df_pax_1.iloc[0,14]*87.4121)
df_pax_1.loc[1,'predict_arriving_passengers'] = round(20.5319 + df_pax_1.iloc[1,5]*-4.1768 + df_pax_1.iloc[1,9]*14.3437 + df_pax_1.iloc[1,10]*-44.9597 + df_pax_1.iloc[1,13]*-32.4347 + df_pax_1.iloc[1,14]*55.8738)
df_pax_1.loc[2,'predict_arriving_passengers'] = round(32.5386 + df_pax_1.iloc[2,5]*-18.7462 + df_pax_1.iloc[2,9]*0.1625 + df_pax_1.iloc[2,10]*-17.9628 + df_pax_1.iloc[2,13]*-45.8880 + df_pax_1.iloc[2,14]*37.7349)
df_pax_1.loc[3,'predict_arriving_passengers'] = round(5.3168 + df_pax_1.iloc[3,5]*11.7892 + df_pax_1.iloc[3,9]*12.9924 + df_pax_1.iloc[3,10]*-37.1013 + df_pax_1.iloc[3,13]*-2.0383 + df_pax_1.iloc[3,14]*17.4583)
df_pax_1.loc[4,'predict_arriving_passengers'] = round(13.6138 + df_pax_1.iloc[4,5]*26.6955 + df_pax_1.iloc[4,9]*-21.9940 + df_pax_1.iloc[4,10]*-6.1591 + df_pax_1.iloc[4,13]*-8.6047 + df_pax_1.iloc[4,14]*29.4489)

In [180]:
df_pax_1

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances,predict_waiting_passengers,predict_departing_passengers,predict_arriving_passengers
0,อาคารจักร,8:00-8:30,0,0,14,0.849092,0.85716,1.0,1.0,0.718367,0.0,0.988372,0.094595,0.0,0.0,0.0,-0.0,-0.0,14.0
1,อาคารจักร,8:30-9:00,0,0,30,0.200150,0.85716,1.0,1.0,0.718367,0.0,0.988372,0.094595,0.0,0.0,0.0,-0.0,-0.0,30.0
2,อาคารจักร,9:00-9:30,3,3,24,0.461711,0.85716,1.0,1.0,0.718367,0.0,0.988372,0.094595,0.0,0.0,0.0,3.0,3.0,24.0
3,อาคารจักร,9:30-10:00,3,4,26,0.962741,0.85716,1.0,1.0,0.718367,0.0,0.988372,0.094595,0.0,0.0,0.0,3.0,4.0,26.0
4,อาคารจักร,10:00-10:30,2,1,9,0.419023,0.85716,1.0,1.0,0.718367,0.0,0.988372,0.094595,0.0,0.0,0.0,2.0,1.0,9.0

# 2.2 Predict stop#2,3

In [181]:
df_pax_2_3 = pd.read_csv("Regression_Data-pax_Stop#2,3.csv")
df_pax_2_3

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,สระว่ายน้ำ,8:00-8:30,NaN,NaN,NaN,2777.00000,16362.000000,1674.00000,236741.0997,155.0000,0.000,77.00,8.000,5,1,1
1,สระว่ายน้ำ,8:30-9:00,NaN,NaN,NaN,834.00000,16362.000000,1674.00000,236741.0997,155.0000,0.000,77.00,8.000,5,1,1
2,สระว่ายน้ำ,9:00-9:30,NaN,NaN,NaN,1476.00000,16362.000000,1674.00000,236741.0997,155.0000,0.000,77.00,8.000,5,1,1
3,สระว่ายน้ำ,9:30-10:00,NaN,NaN,NaN,3593.00000,16362.000000,1674.00000,236741.0997,155.0000,0.000,77.00,8.000,5,1,1
4,สระว่ายน้ำ,10:00-10:30,NaN,NaN,NaN,1498.00000,16362.000000,1674.00000,236741.0997,155.0000,0.000,77.00,8.000,5,1,1
5,ศูนย์หนังสือมก.,8:00-8:30,NaN,NaN,NaN,2347.00000,18513.000000,828.00000,269277.2048,166.0000,6.000,74.00,3.000,36,1,2
6,ศูนย์หนังสือมก.,8:30-9:00,NaN,NaN,NaN,510.00000,18513.000000,828.00000,269277.2048,166.0000,6.000,74.00,3.000,36,1,2
7,ศูนย์หนังสือมก.,9:00-9:30,NaN,NaN,NaN,3401.00000,18513.000000,828.00000,269277.2048,166.0000,6.000,74.00,3.000,36,1,2
8,ศูนย์หนังสือมก.,9:30-10:00,NaN,NaN,NaN,2216.00000,18513.000000,828.00000,269277.2048,166.0000,6.000,74.00,3.000,36,1,2
9,ศูนย์หนังสือมก.,10:00-10:30,NaN,NaN,NaN,927.00000,18513.000000,828.00000,269277.2048,166.0000,6.000,74.00,3.000,36,1,2
10,พหล,8:00-8:30,175.0,145.0,18.0,201.20160,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
11,พหล,8:30-9:00,126.0,110.0,22.0,0.89112,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
12,พหล,9:00-9:30,99.0,90.0,24.0,225.58680,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
13,พหล,9:30-10:00,79.0,74.0,26.0,401.78130,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
14,พหล,10:00-10:30,42.0,42.0,15.0,248.13950,2501.797352,228.83947,101695.5292,71.7057,1.363,42.66,2.868,36,3,2
15,สระน้ำ พหล,8:00-8:30,58.0,97.0,3.0,0.00000,98.000000,27.00000,5270.0000,35.0000,2.000,33.00,2.000,8,2,1
16,สระน้ำ พหล,8:30-9:00,18.0,89.0,2.0,0.00000,98.000000,27.00000,5270.0000,35.0000,2.000,33.00,2.000,8,2,1
17,สระน้ำ พหล,9:00-9:30,16.0,39.0,1.0,159.00000,98.000000,27.00000,5270.0000,35.0000,2.000,33.00,2.000,8,2,1
18,สระน้ำ พหล,9:30-10:00,17.0,58.0,8.0,217.00000,98.000000,27.00000,5270.0000,35.0000,2.000,33.00,2.000,8,2,1
19,สระน้ำ พหล,10:00-10:30,18.0,50.0,16.0,126.00000,98.000000,27.00000,5270.0000,35.0000,2.000,33.00,2.000,8,2,1
20,งาม1,8:00-8:30,71.0,9.0,25.0,447.32000,18090.000000,816.00000,265234.6525,159.0000,6.000,69.00,3.000,13,4,2
21,งาม1,8:30-9:00,111.0,21.0,26.0,317.83000,18090.000000,816.00000,265234.6525,159.0000,6.000,69.00,3.000,13,4,2
22,งาม1,9:00-9:30,66.0,41.0,26.0,2837.62000,18090.000000,816.00000,265234.6525,159.0000,6.000,69.00,3.000,13,4,2
23,งาม1,9:30-10:00,34.0,19.0,33.0,885.59000,18090.000000,816.00000,265234.6525,159.0000,6.000,69.00,3.000,13,4,2
24,งาม1,10:00-10:30,42.0,15.0,8.0,575.56000,18090.000000,816.00000,265234.6525,159.0000,6.000,69.00,3.000,13,4,2
25,งาม3,8:00-8:30,18.0,7.0,2.0,777.00000,14718.000000,560.00000,195262.2497,170.0000,0.000,69.00,5.000,9,1,3
26,งาม3,8:30-9:00,8.0,1.0,4.0,340.00000,14718.000000,560.00000,195262.2497,170.0000,0.000,69.00,5.000,9,1,3
27,งาม3,9:00-9:30,0.0,1.0,3.0,2802.00000,14718.000000,560.00000,195262.2497,170.0000,0.000,69.00,5.000,9,1,3
28,งาม3,9:30-10:00,0.0,0.0,4.0,742.00000,14718.000000,560.00000,195262.2497,170.0000,0.000,69.00,5.000,9,1,3
29,งาม3,10:00-10:30,0.0,0.0,3.0,430.00000,14718.000000,560.00000,195262.2497,170.0000,0.000,69.00,5.000,9,1,3
30,วิภา,8:00-8:30,35.0,2.0,24.0,862.00000,1892.000000,358.00000,93389.1200,99.0000,0.000,6.00,9.000,78,2,1
31,วิภา,8:30-9:00,81.0,54.0,23.0,163.00000,1892.000000,358.00000,93389.1200,99.0000,0.000,6.00,9.000,78,2,1
32,วิภา,9:00-9:30,75.0,50.0,22.0,318.00000,1892.000000,358.00000,93389.1200,99.0000,0.000,6.00,9.000,78,2,1
33,วิภา,9:30-10:00,32.0,18.0,12.0,1474.00000,1892.000000,358.00000,93389.1200,99.0000,0.000,6.00,9.000,78,2,1
34,วิภา,10:00-10:30,23.0,10.0,9.0,244.00000,1892.000000,358.00000,93389.1200,99.0000,0.000,6.00,9.000,78,2,1
35,ศร.1,8:00-8:30,5.0,7.0,20.0,4617.00000,24503.000000,1221.00000,349200.0000,280.0000,5.000,92.00,7.000,0,2,2
36,ศร.1,8:30-9:00,1.0,4.0,15.0,1322.00000,24503.000000,1221.00000,349200.0000,280.0000,5.000,92.00,7.000,0,2,2
37,ศร.1,9:00-9:30,1.0,7.0,14.0,4647.00000,24503.000000,1221.00000,349200.0000,280.0000,5.000,92.00,7.000,0,2,2
38,ศร.1,9:30-10:00,4.0,5.0,5.0,5341.00000,24503.000000,1221.00000,349200.0000,280.0000,5.000,92.00,7.000,0,2,2
39,ศร.1,10:00-10:30,0.0,3.0,6.0,1940.00000,24503.000000,1221.00000,349200.0000,280.0000,5.000,92.00,7.000,0,2,2
40,หอสมุด,8:00-8:30,2.0,8.0,26.0,41.00000,22621.000000,1648.00000,247210.0000,244.0000,1.000,6.00,75.000,71,3,0
41,หอสมุด,8:30-9:00,0.0,4.0,33.0,0.00000,22621.000000,1648.00000,247210.0000,244.0000,1.000,6.00,75.000,71,3,0
42,หอสมุด,9:00-9:30,2.0,0.0,13.0,20.00000,22621.000000,1648.00000,247210.0000,244.0000,1.000,6.00,75.000,71,3,0
43,หอสมุด,9:30-10:00,1.0,10.0,20.0,0.00000,22621.000000,1648.00000,247210.0000,244.0000,1.000,6.00,75.000,71,3,0
44,หอสมุด,10:00-10:30,2.0,10.0,6.0,75.00000,22621.000000,1648.00000,247210.0000,244.0000,1.000,6.00,75.000,71,3,0
45,บาร์ใหม่,8:00-8:30,3.0,6.0,2.0,4218.37982,23519.000000,1470.00000,319558.2243,207.0000,3.000,71.00,8.000,10,1,3
46,บาร์ใหม่,8:30-9:00,0.0,0.0,3.0,1232.26505,23519.000000,1470.00000,319558.2243,207.0000,3.000,71.00,8.000,10,1,3
47,บาร์ใหม่,9:00-9:30,1.0,2.0,4.0,3928.40932,23519.000000,1470.00000,319558.2243,207.0000,3.000,71.00,8.000,10,1,3
48,บาร์ใหม่,9:30-10:00,0.0,0.0,5.0,4246.83225,23519.000000,1470.00000,319558.2243,207.0000,3.000,71.00,8.000,10,1,3
49,บาร์ใหม่,10:00-10:30,2.0,0.0,0.0,1202.36152,23519.000000,1470.00000,319558.2243,207.0000,3.000,71.00,8.000,10,1,3
50,อาคารจักร,8:00-8:30,0.0,0.0,14.0,4535.00000,21017.000000,1972.00000,352377.6914,211.0000,0.000,91.00,8.000,0,1,0
51,อาคารจักร,8:30-9:00,0.0,0.0,30.0,1069.00000,21017.000000,1972.00000,352377.6914,211.0000,0.000,91.00,8.000,0,1,0
52,อาคารจักร,9:00-9:30,3.0,3.0,24.0,2466.00000,21017.000000,1972.00000,352377.6914,211.0000,0.000,91.00,8.000,0,1,0
53,อาคารจักร,9:30-10:00,3.0,4.0,26.0,5142.00000,21017.000000,1972.00000,352377.6914,211.0000,0.000,91.00,8.000,0,1,0
54,อาคารจักร,10:00-10:30,2.0,1.0,9.0,2238.00000,21017.000000,1972.00000,352377.6914,211.0000,0.000,91.00,8.000,0,1,0
55,RDIPT,8:00-8:30,4.0,1.0,32.0,2737.00000,18716.000000,1801.00000,316241.5301,91.0000,0.000,55.00,1.000,10,1,0
56,RDIPT,8:30-9:00,0.0,3.0,19.0,834.00000,18716.000000,1801.00000,316241.5301,91.0000,0.000,55.00,1.000,10,1,0
57,RDIPT,9:00-9:30,10.0,13.0,22.0,1337.00000,18716.000000,1801.00000,316241.5301,91.0000,0.000,55.00,1.000,10,1,0
58,RDIPT,9:30-10:00,0.0,5.0,17.0,4066.00000,18716.000000,1801.00000,316241.5301,91.0000,0.000,55.00,1.000,10,1,0
59,RDIPT,10:00-10:30,7.0,3.0,17.0,1904.00000,18716.000000,1801.00000,316241.5301,91.0000,0.000,55.00,1.000,10,1,0

## min-max normalization

In [182]:
df_paxx_2_3 = df_pax_2_3.iloc[:,5:].copy()
df_paxx_2_3.head()

,#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,2777.0,16362.0,1674.0,236741.0997,155.0,0.0,77.0,8.0,5,1,1
1,834.0,16362.0,1674.0,236741.0997,155.0,0.0,77.0,8.0,5,1,1
2,1476.0,16362.0,1674.0,236741.0997,155.0,0.0,77.0,8.0,5,1,1
3,3593.0,16362.0,1674.0,236741.0997,155.0,0.0,77.0,8.0,5,1,1
4,1498.0,16362.0,1674.0,236741.0997,155.0,0.0,77.0,8.0,5,1,1

In [183]:
normalized_df_paxx_2_3=(df_paxx_2_3-df_paxx_2_3.min())/(df_paxx_2_3.max()-df_paxx_2_3.min())
normalized_df_paxx_2_3.head()

,#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,0.519940,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333
1,0.156151,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333
2,0.276353,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333
3,0.672720,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333
4,0.280472,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333

In [184]:
df_pax_2_3 = pd.concat([df_pax_2_3.iloc[:,:5],normalized_df_paxx_2_3], axis=1)

In [185]:
df_pax_2_3

,location,time,#waiting passengers (y),#departing passengers (y),#arriving passengers (y),#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,สระว่ายน้ำ,8:00-8:30,NaN,NaN,NaN,0.519940,0.666421,0.846787,0.666857,0.489796,0.000000,0.825581,0.094595,0.064103,0.000000,0.333333
1,สระว่ายน้ำ,8:30-9:00,NaN,NaN,NaN,0.156151,0.666421,0.846787,0.666857,0.489796,0.000000,0.825581,0.094595,0.064103,0.000000,0.333333
2,สระว่ายน้ำ,9:00-9:30,NaN,NaN,NaN,0.276353,0.666421,0.846787,0.666857,0.489796,0.000000,0.825581,0.094595,0.064103,0.000000,0.333333
3,สระว่ายน้ำ,9:30-10:00,NaN,NaN,NaN,0.672720,0.666421,0.846787,0.666857,0.489796,0.000000,0.825581,0.094595,0.064103,0.000000,0.333333
4,สระว่ายน้ำ,10:00-10:30,NaN,NaN,NaN,0.280472,0.666421,0.846787,0.666857,0.489796,0.000000,0.825581,0.094595,0.064103,0.000000,0.333333
5,ศูนย์หนังสือมก.,8:00-8:30,NaN,NaN,NaN,0.439431,0.754558,0.411825,0.760592,0.534694,1.000000,0.790698,0.027027,0.461538,0.000000,0.666667
6,ศูนย์หนังสือมก.,8:30-9:00,NaN,NaN,NaN,0.095488,0.754558,0.411825,0.760592,0.534694,1.000000,0.790698,0.027027,0.461538,0.000000,0.666667
7,ศูนย์หนังสือมก.,9:00-9:30,NaN,NaN,NaN,0.636772,0.754558,0.411825,0.760592,0.534694,1.000000,0.790698,0.027027,0.461538,0.000000,0.666667
8,ศูนย์หนังสือมก.,9:30-10:00,NaN,NaN,NaN,0.414904,0.754558,0.411825,0.760592,0.534694,1.000000,0.790698,0.027027,0.461538,0.000000,0.666667
9,ศูนย์หนังสือมก.,10:00-10:30,NaN,NaN,NaN,0.173563,0.754558,0.411825,0.760592,0.534694,1.000000,0.790698,0.027027,0.461538,0.000000,0.666667
10,พหล,8:00-8:30,175.0,145.0,18.0,0.037671,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
11,พหล,8:30-9:00,126.0,110.0,22.0,0.000167,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
12,พหล,9:00-9:30,99.0,90.0,24.0,0.042237,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
13,พหล,9:30-10:00,79.0,74.0,26.0,0.075226,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
14,พหล,10:00-10:30,42.0,42.0,15.0,0.046459,0.098496,0.103774,0.277797,0.149819,0.227167,0.426279,0.025243,0.461538,0.666667,0.666667
15,สระน้ำ พหล,8:00-8:30,58.0,97.0,3.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
16,สระน้ำ พหล,8:30-9:00,18.0,89.0,2.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
17,สระน้ำ พหล,9:00-9:30,16.0,39.0,1.0,0.029770,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
18,สระน้ำ พหล,9:30-10:00,17.0,58.0,8.0,0.040629,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
19,สระน้ำ พหล,10:00-10:30,18.0,50.0,16.0,0.023591,0.000000,0.000000,0.000000,0.000000,0.333333,0.313953,0.013514,0.102564,0.333333,0.333333
20,งาม1,8:00-8:30,71.0,9.0,25.0,0.083752,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
21,งาม1,8:30-9:00,111.0,21.0,26.0,0.059508,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
22,งาม1,9:00-9:30,66.0,41.0,26.0,0.531290,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
23,งาม1,9:30-10:00,34.0,19.0,33.0,0.165810,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
24,งาม1,10:00-10:30,42.0,15.0,8.0,0.107763,0.737226,0.405656,0.748945,0.506122,1.000000,0.732558,0.027027,0.166667,1.000000,0.666667
25,งาม3,8:00-8:30,18.0,7.0,2.0,0.145478,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
26,งาม3,8:30-9:00,8.0,1.0,4.0,0.063658,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
27,งาม3,9:00-9:30,0.0,1.0,3.0,0.524621,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
28,งาม3,9:30-10:00,0.0,0.0,4.0,0.138925,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
29,งาม3,10:00-10:30,0.0,0.0,3.0,0.080509,0.599058,0.274036,0.547358,0.551020,0.000000,0.732558,0.054054,0.115385,0.000000,1.000000
30,วิภา,8:00-8:30,35.0,2.0,24.0,0.161393,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
31,วิภา,8:30-9:00,81.0,54.0,23.0,0.030519,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
32,วิภา,9:00-9:30,75.0,50.0,22.0,0.059539,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
33,วิภา,9:30-10:00,32.0,18.0,12.0,0.275978,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
34,วิภา,10:00-10:30,23.0,10.0,9.0,0.045684,0.073510,0.170180,0.253867,0.261224,0.000000,0.000000,0.108108,1.000000,0.333333,0.333333
35,ศร.1,8:00-8:30,5.0,7.0,20.0,0.864445,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
36,ศร.1,8:30-9:00,1.0,4.0,15.0,0.247519,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
37,ศร.1,9:00-9:30,1.0,7.0,14.0,0.870062,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
38,ศร.1,9:30-10:00,4.0,5.0,5.0,1.000000,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
39,ศร.1,10:00-10:30,0.0,3.0,6.0,0.363228,1.000000,0.613882,0.990845,1.000000,0.833333,1.000000,0.081081,0.000000,0.333333,0.666667
40,หอสมุด,8:00-8:30,2.0,8.0,26.0,0.007676,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
41,หอสมุด,8:30-9:00,0.0,4.0,33.0,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
42,หอสมุด,9:00-9:30,2.0,0.0,13.0,0.003745,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
43,หอสมุด,9:30-10:00,1.0,10.0,20.0,0.000000,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
44,หอสมุด,10:00-10:30,2.0,10.0,6.0,0.014042,0.922885,0.833419,0.697017,0.853061,0.166667,0.000000,1.000000,0.910256,0.666667,0.000000
45,บาร์ใหม่,8:00-8:30,3.0,6.0,2.0,0.789811,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
46,บาร์ใหม่,8:30-9:00,0.0,0.0,3.0,0.230718,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
47,บาร์ใหม่,9:00-9:30,1.0,2.0,4.0,0.735519,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
48,บาร์ใหม่,9:30-10:00,0.0,0.0,5.0,0.795138,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
49,บาร์ใหม่,10:00-10:30,2.0,0.0,0.0,0.225119,0.959680,0.741902,0.905449,0.702041,0.500000,0.755814,0.094595,0.128205,0.000000,1.000000
50,อาคารจักร,8:00-8:30,0.0,0.0,14.0,0.849092,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
51,อาคารจักร,8:30-9:00,0.0,0.0,30.0,0.200150,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
52,อาคารจักร,9:00-9:30,3.0,3.0,24.0,0.461711,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
53,อาคารจักร,9:30-10:00,3.0,4.0,26.0,0.962741,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
54,อาคารจักร,10:00-10:30,2.0,1.0,9.0,0.419023,0.857160,1.000000,1.000000,0.718367,0.000000,0.988372,0.094595,0.000000,0.000000,0.000000
55,RDIPT,8:00-8:30,4.0,1.0,32.0,0.512451,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
56,RDIPT,8:30-9:00,0.0,3.0,19.0,0.156151,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
57,RDIPT,9:00-9:30,10.0,13.0,22.0,0.250328,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
58,RDIPT,9:30-10:00,0.0,5.0,17.0,0.761281,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000
59,RDIPT,10:00-10:30,7.0,3.0,17.0,0.356488,0.762876,0.912082,0.895894,0.228571,0.000000,0.569767,0.000000,0.128205,0.000000,0.000000

## Predict stop#2

### use model from inside U

In [186]:
df_pax_2 = df_pax_2_3[df_pax_2_3['location'] == 'สระว่ายน้ำ']
df_pax_2 = df_pax_2.rename(columns={"#waiting passengers (y)": "predict_waiting_passengers", "#departing passengers (y)": "predict_departing_passengers", "#arriving passengers (y)": "predict_arriving_passengers"})
df_pax_2

,location,time,predict_waiting_passengers,predict_departing_passengers,predict_arriving_passengers,#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,สระว่ายน้ำ,8:00-8:30,NaN,NaN,NaN,0.519940,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333
1,สระว่ายน้ำ,8:30-9:00,NaN,NaN,NaN,0.156151,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333
2,สระว่ายน้ำ,9:00-9:30,NaN,NaN,NaN,0.276353,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333
3,สระว่ายน้ำ,9:30-10:00,NaN,NaN,NaN,0.672720,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333
4,สระว่ายน้ำ,10:00-10:30,NaN,NaN,NaN,0.280472,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333

In [187]:
df_pax_2.loc[0,'predict_waiting_passengers'] = round(28.8861 + df_pax_2.iloc[0,6]*-32.6850 + df_pax_2.iloc[0,9]*-1.2109 + df_pax_2.iloc[0,10]*12.0117 + df_pax_2.iloc[0,13]*2.5370)
df_pax_2.loc[1,'predict_waiting_passengers'] = round(8.2704 + df_pax_2.iloc[1,6]*-11.5199 + df_pax_2.iloc[1,9]*2.2328 + df_pax_2.iloc[1,10]*2.4200 + df_pax_2.iloc[1,13]*0.0583)
df_pax_2.loc[2,'predict_waiting_passengers'] = round(62.4800 + df_pax_2.iloc[2,6]*-69.0328 + df_pax_2.iloc[2,9]*-0.4284 + df_pax_2.iloc[2,10]*9.5775 + df_pax_2.iloc[2,13]*2.1956)
df_pax_2.loc[3,'predict_waiting_passengers'] = round(30.7063 + df_pax_2.iloc[3,6]*-44.1827 + df_pax_2.iloc[3,9]*14.1506 + df_pax_2.iloc[3,10]*3.9909 + df_pax_2.iloc[3,13]*-1.8317)
df_pax_2.loc[4,'predict_waiting_passengers'] = round(20.3079 + df_pax_2.iloc[4,6]*-15.7009 + df_pax_2.iloc[4,9]*-6.7510 + df_pax_2.iloc[4,10]*2.5728 + df_pax_2.iloc[4,13]*1.6616)

In [188]:
df_pax_2.loc[0,'predict_departing_passengers'] = round(9.0913 + df_pax_2.iloc[0,6]*-10.6063 + df_pax_2.iloc[0,10]*-1.3403 + df_pax_2.iloc[0,14]*13.3807 + df_pax_2.iloc[0,15]*7.7575)
df_pax_2.loc[1,'predict_departing_passengers'] = round(27.2738 + df_pax_2.iloc[1,6]*-31.8188 + df_pax_2.iloc[1,10]*7.9791 + df_pax_2.iloc[1,14]*7.1421 + df_pax_2.iloc[1,15]*-0.7275)
df_pax_2.loc[2,'predict_departing_passengers'] = round(93.9126 + df_pax_2.iloc[2,6]*-106.0626 + df_pax_2.iloc[2,10]*25.3971 + df_pax_2.iloc[2,14]*-0.3930 + df_pax_2.iloc[2,15]*-2.8250)
df_pax_2.loc[3,'predict_departing_passengers'] = round(13.0913 + df_pax_2.iloc[3,6]*-10.6063 + df_pax_2.iloc[3,10]*2.6597 + df_pax_2.iloc[3,14]*9.3807 + df_pax_2.iloc[3,15]*-4.2425)
df_pax_2.loc[4,'predict_departing_passengers'] = round(19.1825 + df_pax_2.iloc[4,6]*-21.2125 + df_pax_2.iloc[4,10]*-2.2806 + df_pax_2.iloc[4,14]*16.1614 + df_pax_2.iloc[4,15]*2.3150)

In [189]:
df_pax_2.loc[0,'predict_arriving_passengers'] = round(54.5886 + df_pax_2.iloc[0,5]*-11.8413 + df_pax_2.iloc[0,9]*-42.5051 + df_pax_2.iloc[0,10]*-13.1817 + df_pax_2.iloc[0,13]*-53.0796 + df_pax_2.iloc[0,14]*87.4121)
df_pax_2.loc[1,'predict_arriving_passengers'] = round(20.5319 + df_pax_2.iloc[1,5]*-4.1768 + df_pax_2.iloc[1,9]*14.3437 + df_pax_2.iloc[1,10]*-44.9597 + df_pax_2.iloc[1,13]*-32.4347 + df_pax_2.iloc[1,14]*55.8738)
df_pax_2.loc[2,'predict_arriving_passengers'] = round(32.5386 + df_pax_2.iloc[2,5]*-18.7462 + df_pax_2.iloc[2,9]*0.1625 + df_pax_2.iloc[2,10]*-17.9628 + df_pax_2.iloc[2,13]*-45.8880 + df_pax_2.iloc[2,14]*37.7349)
df_pax_2.loc[3,'predict_arriving_passengers'] = round(5.3168 + df_pax_2.iloc[3,5]*11.7892 + df_pax_2.iloc[3,9]*12.9924 + df_pax_2.iloc[3,10]*-37.1013 + df_pax_2.iloc[3,13]*-2.0383 + df_pax_2.iloc[3,14]*17.4583)
df_pax_2.loc[4,'predict_arriving_passengers'] = round(13.6138 + df_pax_2.iloc[4,5]*26.6955 + df_pax_2.iloc[4,9]*-21.9940 + df_pax_2.iloc[4,10]*-6.1591 + df_pax_2.iloc[4,13]*-8.6047 + df_pax_2.iloc[4,14]*29.4489)

In [190]:
df_pax_2

,location,time,predict_waiting_passengers,predict_departing_passengers,predict_arriving_passengers,#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,สระว่ายน้ำ,8:00-8:30,7.0,5.0,24.0,0.519940,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333
1,สระว่ายน้ำ,8:30-9:00,2.0,6.0,25.0,0.156151,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333
2,สระว่ายน้ำ,9:00-9:30,16.0,22.0,24.0,0.276353,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333
3,สระว่ายน้ำ,9:30-10:00,8.0,5.0,19.0,0.672720,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333
4,สระว่ายน้ำ,10:00-10:30,7.0,6.0,10.0,0.280472,0.666421,0.846787,0.666857,0.489796,0.0,0.825581,0.094595,0.064103,0.0,0.333333

## Predict stop#3

### use model from education building

In [191]:
df_pax_3 = df_pax_2_3[df_pax_2_3['location'] == 'ศูนย์หนังสือมก.']
df_pax_3 = df_pax_3.rename(columns={"#waiting passengers (y)": "predict_waiting_passengers", "#departing passengers (y)": "predict_departing_passengers", "#arriving passengers (y)": "predict_arriving_passengers"})
df_pax_3 = df_pax_3.reset_index(drop=True)
df_pax_3

,location,time,predict_waiting_passengers,predict_departing_passengers,predict_arriving_passengers,#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,ศูนย์หนังสือมก.,8:00-8:30,NaN,NaN,NaN,0.439431,0.754558,0.411825,0.760592,0.534694,1.0,0.790698,0.027027,0.461538,0.0,0.666667
1,ศูนย์หนังสือมก.,8:30-9:00,NaN,NaN,NaN,0.095488,0.754558,0.411825,0.760592,0.534694,1.0,0.790698,0.027027,0.461538,0.0,0.666667
2,ศูนย์หนังสือมก.,9:00-9:30,NaN,NaN,NaN,0.636772,0.754558,0.411825,0.760592,0.534694,1.0,0.790698,0.027027,0.461538,0.0,0.666667
3,ศูนย์หนังสือมก.,9:30-10:00,NaN,NaN,NaN,0.414904,0.754558,0.411825,0.760592,0.534694,1.0,0.790698,0.027027,0.461538,0.0,0.666667
4,ศูนย์หนังสือมก.,10:00-10:30,NaN,NaN,NaN,0.173563,0.754558,0.411825,0.760592,0.534694,1.0,0.790698,0.027027,0.461538,0.0,0.666667

In [192]:
df_pax_3.loc[0,'predict_waiting_passengers'] = round(17.0574 + df_pax_3.iloc[0,5]*-15.7722 + df_pax_3.iloc[0,6]*-4.2762 + df_pax_3.iloc[0,10]*7.0235 + df_pax_3.iloc[0,13]*-13.3595)
df_pax_3.loc[1,'predict_waiting_passengers'] = round(0.2380 + df_pax_3.iloc[1,5]*0.0611 + df_pax_3.iloc[1,6]*-0.2919 + df_pax_3.iloc[1,10]*1.2466 + df_pax_3.iloc[1,13]*-0.1937)
df_pax_3.loc[2,'predict_waiting_passengers'] = round(38.1343 + df_pax_3.iloc[2,5]*-36.7525 + df_pax_3.iloc[2,6]*-21.1924 + df_pax_3.iloc[2,10]*19.2420 + df_pax_3.iloc[2,13]*-21.5825)
df_pax_3.loc[3,'predict_waiting_passengers'] = round(-22.1341 + df_pax_3.iloc[3,5]*4.8541 + df_pax_3.iloc[3,6]*23.8705 + df_pax_3.iloc[3,10]*-3.1086 + df_pax_3.iloc[3,13]*1.7825)
df_pax_3.loc[4,'predict_waiting_passengers'] = round(41.6492 + df_pax_3.iloc[4,5]*8.1852 + df_pax_3.iloc[4,6]*-50.2577 + df_pax_3.iloc[4,10]*6.7626 + df_pax_3.iloc[4,13]*6.0322)

In [193]:
df_pax_3.loc[0,'predict_departing_passengers'] = round(2.1324 + df_pax_3.iloc[0,6]*-2.4878 + df_pax_3.iloc[0,10]*7.9879 + df_pax_3.iloc[0,13]*5.9705 + df_pax_3.iloc[0,14]*2.0963)
df_pax_3.loc[1,'predict_departing_passengers'] = round(13.2013 + df_pax_3.iloc[1,6]*-15.4012 + df_pax_3.iloc[1,10]*12.2518 + df_pax_3.iloc[1,13]*12.0737 + df_pax_3.iloc[1,14]*-12.0298)
df_pax_3.loc[2,'predict_departing_passengers'] = round(52.7970 + df_pax_3.iloc[2,6]*-58.0953 + df_pax_3.iloc[2,10]*37.2590 + df_pax_3.iloc[2,13]*35.2759 + df_pax_3.iloc[2,14]*-56.2525)
df_pax_3.loc[3,'predict_departing_passengers'] = round(5.2515 + df_pax_3.iloc[3,6]*-1.4601 + df_pax_3.iloc[3,10]*1.6292 + df_pax_3.iloc[3,13]*6.7262 + df_pax_3.iloc[3,14]*-0.4473)
df_pax_3.loc[4,'predict_departing_passengers'] = round(6.3557 + df_pax_3.iloc[4,6]*-6.2482 + df_pax_3.iloc[4,10]*4.2611 + df_pax_3.iloc[4,13]*11.0050 + df_pax_3.iloc[4,14]*-1.9753)

In [194]:
df_pax_3.loc[0,'predict_arriving_passengers'] = round(10.9100 + df_pax_3.iloc[0,6]*31.8436 + df_pax_3.iloc[0,9]*-57.9412 + df_pax_3.iloc[0,11]*17.6229 + df_pax_3.iloc[0,14]*52.6940)
df_pax_3.loc[1,'predict_arriving_passengers'] = round(51.8447 + df_pax_3.iloc[1,6]*-20.7280 + df_pax_3.iloc[1,9]*79.1245 + df_pax_3.iloc[1,11]*-61.6346 + df_pax_3.iloc[1,14]*-100.8197)
df_pax_3.loc[2,'predict_arriving_passengers'] = round(29.0412 + df_pax_3.iloc[2,6]*-2.7187 + df_pax_3.iloc[2,9]*18.34835 + df_pax_3.iloc[2,11]*-16.0786 + df_pax_3.iloc[2,14]*-43.7765)
df_pax_3.loc[3,'predict_arriving_passengers'] = round(54.3382 + df_pax_3.iloc[3,6]*-25.1637 + df_pax_3.iloc[3,9]*76.7429 + df_pax_3.iloc[3,11]*-62.6267 + df_pax_3.iloc[3,14]*-114.8722)
df_pax_3.loc[4,'predict_arriving_passengers'] = round(11.8806 + df_pax_3.iloc[4,6]*10.2202 + df_pax_3.iloc[4,9]*-21.7375 + df_pax_3.iloc[4,11]*4.0213 + df_pax_3.iloc[4,14]*4.8462)

In [195]:
df_pax_3

,location,time,predict_waiting_passengers,predict_departing_passengers,predict_arriving_passengers,#students from buildings,#students from faculties,#lecturers from faculties,faculty area,#stores,#banks,#offices,#dorms,#waiting seats,#routes,#main entrances
0,ศูนย์หนังสือมก.,8:00-8:30,8.0,11.0,18.0,0.439431,0.754558,0.411825,0.760592,0.534694,1.0,0.790698,0.027027,0.461538,0.0,0.666667
1,ศูนย์หนังสือมก.,8:30-9:00,1.0,19.0,30.0,0.095488,0.754558,0.411825,0.760592,0.534694,1.0,0.790698,0.027027,0.461538,0.0,0.666667
2,ศูนย์หนังสือมก.,9:00-9:30,8.0,63.0,24.0,0.636772,0.754558,0.411825,0.760592,0.534694,1.0,0.790698,0.027027,0.461538,0.0,0.666667
3,ศูนย์หนังสือมก.,9:30-10:00,-4.0,9.0,27.0,0.414904,0.754558,0.411825,0.760592,0.534694,1.0,0.790698,0.027027,0.461538,0.0,0.666667
4,ศูนย์หนังสือมก.,10:00-10:30,15.0,11.0,11.0,0.173563,0.754558,0.411825,0.760592,0.534694,1.0,0.790698,0.027027,0.461538,0.0,0.666667